### ISSUE TITLE
iPXE Integration

### ISSUE THREAD

**Issue by NefixEstrada** [isard-vdi/isard#11]
Integrate the [isard-ipxe](https://github.com/isard-vdi/isard-ipxe) project. Add documentation and merge the changes in the old `pxe` branch

**Comment by jvinolas** [comment]
What is it needed to test this now? Can I bring up complete iPXE dockers from your actual pxe branch?

**Comment by NefixEstrada** [comment]
Currently, the "API" returns the names of the desktops with accents. Those should be parsed and removed, since iPXE can't show them and shows an ugly character instead.

What would be needed is something like:
`é` -> `e`
`ü` -> `u`
`ç` -> `c`
...

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
