### ISSUE TITLE
Wizard incorrect titles

### ISSUE THREAD

**Issue by NefixEstrada** [isard-vdi/isard#122]
At the Wizard, the step 4 and 5 have the title number changed:
![screenshot](https://user-images.githubusercontent.com/22214853/53415294-2ac4cf00-39d1-11e9-8ee9-d68a9ea79e5a.png)

**Comment by jvinolas** [comment]
This one was quick. Almost at the release time! ;-)

**Comment by NefixEstrada** [comment]
I've scheduled it for `1.2.0`. It's not a critical bug and can wait for the next release. The release branch has already been freezed

**Comment by NefixEstrada** [comment]
This issue has already been fixed, not sure when though :woman_shrugging:
