### ISSUE TITLE
[QUESTION] Rest API documentation

### ISSUE THREAD

**Issue by b-barry** [isard-vdi/isard#142]
Hello,

I would like to manage the web-app programmatically using a REST API. However, I didn't find any documentation i.e swagger for example about all the API calls.
So do you plan to provide it?

Kinds regards,
Bouba

**Comment by jvinolas** [comment]
We have plans to rebuild UI and change the current Flask model to Vue.js and provide a full REST API. Right now we have some seleniums that automate things. If you want we can provide some.

**Comment by b-barry** [comment]
Wonderful :). I was planning to ask you if you will be interested to rebuild the frontend in vue.js because you could get more contributors like that.

I have a good experience in Vue.js so I could help. We are experimenting it now with some colleagues.

Regarding the automation, now people are using Cypress for e2e test and the setup is built-in with the Vue CLI.

What is the roadmap?

**Comment by jvinolas** [comment]
What exactly do you need now to be automated now? Now we did an auto creation of desktops #134  for users and desktop stop/delete timeouts #133 

We are now doing some premilinary tests with Vue. We plan to rebuild de login and user interface first and then rebuild the admin part. No planned date now. Sure it won't be in 1.2, but maybe we will have work in progress for 1.3

**Comment by b-barry** [comment]
If you have a canary branch for Vue, I could help you in the setup and do some task to know better the code

**Comment by jvinolas** [comment]
We are only doing tests to see if we could get what's needed for the new interface (basically testing vue-socketio, authentication, ...), but nothing structured yet. As soon as we have a basic schema we will publish that branch and let you know. Thanks!!

**Comment by b-barry** [comment]
Ok, nice. If you have any questions about Vue, I will be happy to help to answer them.

**Comment by NefixEstrada** [comment]
We're going to start working on the new frontend today. It's going to use Vue.js and GRPC (plus a RESTful API) for the communication with the server. We'll let you know when it's ready for contributors!

**Comment by b-barry** [comment]
Happy to hear it. Just a question: why do you choose gRPC ? what about GraphQL for the frontend?

**Comment by NefixEstrada** [comment]
We've evaluated both options and we think that gRPC is a better fit for the needs of the project. Also, I already know gRPC so... :smile:

**Comment by NefixEstrada** [comment]
Btw, you can keep track of the progress [here](https://github.com/NefixEstrada/isard/tree/feature/webapp/api)
