### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by NefixEstrada** [isard-vdi/isard#144]
This issue is going to be a place to track the changes that are needed to implement the API and the new frontend

- [ ] Remove the `fl-` in the front of the icons in the DB
- [ ] Migrate the old `isard.conf` to the new configuration system

**Comment by jvinolas** [comment]
- [ ] Fix all int fields in database that now are stored as strings (viewer ports, hypervisor port, etc...)
- [ ] Allowed dict field for permissions should get a new field to set permissions for all the system
- [ ] Think about grpc stream for quotas.

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
