### ISSUE TITLE
Cannot create new "Video" Resource

### ISSUE THREAD

**Issue by inzanez** [isard-vdi/isard#153]
Hi

just installed the docker container and tried out several things. As I was particularly interested in multi-head workstations, I wanted to add some other video settings in the resources. But somehow that doesn't work. I receive errors in the Javascript console with Firefox / Chrome / Chromium. So I guess there's something wrong with that specific piece of Javascript...

**Comment by NefixEstrada** [comment]
Hey there!

Could you please provide more information about what you're trying to do, what things you've been trying and which is the error? It's quite hard to know what's going on without anything!

Thanks! :smile:

**Comment by inzanez** [comment]
Hi

agree. I'm sorry, I had already cleaned up the system when I wrote this. I just installed the docker container once more and tried:
Domains -> Resources -> Add new [for Video]

I entered "Test" as Name, "Test" as a Model and clicked on "Add video". Nothing happens, the modal doesn't close. The console shows:
Error: Syntax error, unrecognized expression: [object Object] #a-roles jquery.js:2:12556

Hope that helps, otherwise I can create screenshots.

**Comment by jvinolas** [comment]
This seems a bug in UI we should fix. Also this domain resources need documentation in readthedocs.

**Comment by sim6** [comment]
Closed due to gitlab issue number conflict.

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
