### ISSUE TITLE
Should we remove `install-docker.sh`?

### ISSUE THREAD

**Issue by NefixEstrada** [isard-vdi/isard#162]
This file is completely useless and might confuse the users. What do you think? Should we remove it?

**Comment by NefixEstrada** [comment]
`dockers/app/Dockerfile_devel` should also be removed

**Comment by sim6** [comment]
install-docker.sh deleted via #193 
dockers/app/Dockerfile_devel deleted via #195

**Comment by NefixEstrada** [comment]
Great!
