### ISSUE TITLE
Cannot access to Grafana

### ISSUE THREAD

**Issue by samuak8** [isard-vdi/isard#163]
Hi team,

We are trying to enter to Grafana for monitoring Isard, but can't find the proper way to access. We set the settings of grafana, and everything seems to be right configured. But doesn't works.

Could you help us? Thanks a lot!

**Comment by samuak8** [comment]
![image](https://user-images.githubusercontent.com/37220575/58039399-f4f83800-7b32-11e9-9994-635b571715fe.png)

**Comment by NefixEstrada** [comment]
Hey!

How are you running Grafana? Have you followed the [documentation](https://isardvdi.readthedocs.io/en/latest/extras/grafana/)?

**Comment by sim6** [comment]
I'm closing this issue due to lack of feedback but, please, feel free to add more comments if you want more support.
