### ISSUE TITLE
Error when "Update"

### ISSUE THREAD

**Issue by a2085419** [isard-vdi/isard#164]
Hello,
My Isard It's running on Ubuntu Server 18.04.2, I don't have the firewall enabled and I have the port 5050 (UDP and TCP), opened (redirecting by NAT to my local address) in the router.

When I click on tab "updates" I get "It could be a network problem or we are currently updating IsardVDI oline updates server"
![updates_error_isardVDI](https://user-images.githubusercontent.com/50824734/58089415-f70ad700-7bc4-11e9-89cb-053e3346c171.PNG)

I could have more information to be able to check that it's a connection problem ?
A lot of thanks.

**Comment by a2085419** [comment]
I have solved.
I had antimalware protection on my router blocking the outgoing packet to Isard server updates.
Thanks.

**Comment by NefixEstrada** [comment]
Thank you and sorry for not answering before!
