### ISSUE TITLE
Machine status creating

### ISSUE THREAD

**Issue by samuak8** [isard-vdi/isard#165]
Hello, we are trying to create machine by a template, but they hold the status creating always, and we don't find any solution to this issue. 

Thanks

**Comment by samuak8** [comment]
![image](https://user-images.githubusercontent.com/37220575/58484011-8eda6900-8161-11e9-81da-58e914494089.png)

**Comment by NefixEstrada** [comment]
Hello!

This seems an engine issue. It's probably going to be solved by stopping and starting IsardVDI again. This is accomplished by executing:

```sh
sudo docker-compose down
sudo docker-compose up -d
```

**Comment by sim6** [comment]
I'm closing this issue due to lack of feedback but, please, feel free to add more comments if you want more support.

**Comment by nicrieser** [comment]
got the same problem, my machine crashed and now it wont leave stopping state. Even when i restart Isard it still wont stop or get status failed.

**Comment by sim6** [comment]
Please, could you check the status of hypervidor via hypervisor menú?

**Comment by nicrieser** [comment]
Ill take a look tomorrow

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
