### ISSUE TITLE
There's no persistence for user defined networks

### ISSUE THREAD

**Issue by NefixEstrada** [isard-vdi/isard#168]
If I add a new network in the `isard-hypervisor` through `virsh net-define network.xml` it's going to be deleted when Isard is stopped (`docker-compose down`).

It should persist through different startups

**Comment by sim6** [comment]
Closed due gitlab issue number conflict.

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
