### ISSUE TITLE
User bulk create can not import 200 users at a time

### ISSUE THREAD

**Issue by sim6** [isard-vdi/isard#169]
Can import 50 users at a time works.

**Comment by jvinolas** [comment]
This can easily be solved (or at least improved). I think now it is coded so it will do a new insert for each user in csv. But we could just create the whole users list and insert them at once in the database.

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
