### ISSUE TITLE
Migrate to gitlab

### ISSUE THREAD

**Issue by sim6** [isard-vdi/isard#170]
To support open source initiatives ;-)

**Comment by NefixEstrada** [comment]
I'd also would like to migrate the development to Gitlab. The fact that Gitlab is Free Software is just one of the many advantages that, in my opinion, has.

That being said, I also think that the GitHub project should be kept as a mirror, because it gives a lot of visibility to the project. This could be archieved using a post-push hook in the Gitlab repository

**Comment by sim6** [comment]
I talked with @jvinolas and @alarraz. We agree move the main development activity to gitlab.com at v2 release time.

**Comment by sim6** [comment]
In order to build docker images with gitlab.com CI (#246) I created https://gitlab.com/isard/isardvdi currently as mirror.

**Comment by sim6** [comment]
Changed docker-compose.yml URL from README.md (#264). Now is github independent.

**Comment by sim6** [comment]
I created also the docs repository https://gitlab.com/isard/isardvdi-docs. Currently as a mirror waiting for https://github.com/isard-vdi/docs/pull/62. 

https://isardvdi.readthedocs.io/ is now fetching the content form Gitlab.

**Comment by sim6** [comment]
Now the https://github.com/isard-vdi/docs/pull/62 changes the docker-compose instructions to be github independent.

**Comment by sim6** [comment]
I closed https://github.com/isard-vdi/docs in favour of https://gitlab.com/isard/isardvdi-docs.

**Comment by sim6** [comment]
I created a merge request to change documentation repository links from github.com to gitlab.com
https://gitlab.com/isard/isardvdi-docs/-/merge_requests/2

**Comment by jvinolas** [comment]
Nice! We can close this one?

**Comment by sim6** [comment]
I prefer to keep it opened until the following work was done.

- [ ] Merge https://gitlab.com/isard/isardvdi-docs/-/merge_requests/2
- [ ] Update CONTRIBUTING.md

**Comment by sim6** [comment]
https://gitlab.com/isard/isardvdi.com/-/merge_requests/1
