### ISSUE TITLE
docker-compose up does not work on Mac

### ISSUE THREAD

**Issue by plebanip** [isard-vdi/isard#174]
I am trying to run your nice tool on a macbook but, while the “docker-compose pull” command perfectly works, when I run the composition with “docker-compose up -d” command I got the following error

WARNING: The TAG variable is not set. Defaulting to a blank string.
Creating volume "isardvdi_sshkeys" with default driver
ERROR: no such image: isard/hypervisor:: invalid reference format

Any suggestion?

Thanks

**Comment by sim6** [comment]
Please could you try the following command:

```
TAG=1 docker-compose up -d
```

Thanks

**Comment by plebanip** [comment]
thanks for the prompt answer.

I got this error now.

Cannot start service isard-database: error while creating mount source path '/etc/localtime': mkdir /etc/localtime: file exists

Is there any modification to the docker-compose.yaml to avoid the need to replace this file?

**Comment by sim6** [comment]
Do you have /etc/localtime in your host?

**Comment by plebanip** [comment]
> Do you have /etc/localtime in your host?

yes. I tried to rename the existing file, but some running apps start complaining.

**Comment by sim6** [comment]
So, please, could you try to run the following command?

```
TAG=latest TZ=$(basename $(readlink /etc/localtime)) docker-compose up -d
```

**Comment by plebanip** [comment]
nope :-( Here is the error

Creating isard-database   ... error
Creating isard-hypervisor ... 

Creating isard-hypervisor ... error

ERROR: for isard-hypervisor  Cannot start service isard-hypervisor: error while creating mount source path '/etc/localtime': mkdir /etc/localtime: file exists

ERROR: for isard-database  Cannot start service isard-database: error while creating mount source path '/etc/localtime': mkdir /etc/localtime: file exists

ERROR: for isard-hypervisor  Cannot start service isard-hypervisor: error while creating mount source path '/etc/localtime': mkdir /etc/localtime: file exists
ERROR: Encountered errors while bringing up the project.

**Comment by sim6** [comment]
Please, could you try my new yml runing the following commands?
```
wget -O docker-compose.yml https://raw.githubusercontent.com/sim6/isard/sim6_fix_docker_compose_github_174/docker-compose.yml
docker-compose pull
LOCALTIME=$(readlink /etc/localtime) docker-compose up -d
```

**Comment by plebanip** [comment]
With your command the error is the same

Then I tried with the absolute link

sudo TAG=latest LOCALTIME=/private/var/db/timezone/zoneinfo/Europe/Rome docker-compose up -d

getting

Cannot start service isard-database: error while creating mount source path '/private/var/db/timezone/zoneinfo/Europe/Rome': mkdir /private/var/db/timezone/zoneinfo: file exists

**Comment by sim6** [comment]
:( Please take a look at https://github.com/docker/for-mac/issues/2396

**Comment by sim6** [comment]
TAG variable no more needed after #175 was merged

**Comment by plebanip** [comment]
being a side project, I had time only in these days to have a look. Anyway, investigating all the solutions that have been proposed, the only one working for me is https://github.com/docker/for-mac/issues/2396#issuecomment-370033847

Not that elegant, but at least isardvdi starts.

I think the issue can be closed. Thanks for the nice support

**Comment by NefixEstrada** [comment]
Thank you too!
