### ISSUE TITLE
windows 10 can't find any storage to install on

### ISSUE THREAD

**Issue by encryptblockr** [isard-vdi/isard#181]
Trying to create desktop from windows 10 ISO and installation can't find storage

![image](https://user-images.githubusercontent.com/35294766/63141623-6c175e00-bfb4-11e9-9494-7ad8ae6f6b81.png)

and here are the specs

![image](https://user-images.githubusercontent.com/35294766/63141786-011a5700-bfb5-11e9-88f8-7b2716e697e1.png)

i also have the drivers installed

![image](https://user-images.githubusercontent.com/35294766/63141817-28712400-bfb5-11e9-8487-03b7d276e5de.png)

**Comment by NefixEstrada** [comment]
You need to add the Virtio drivers to the desktop. This can be done by editing the desktop (what is shown in the 2nd screenshot), clicking to the side of "windows 10 iso" and adding the drivers ISO. (it has to have the two isos to work properly)

**Comment by encryptblockr** [comment]
it does not show the windows driver to add
it only shows all media i downloaded under "media" tab
please see screenshot below

![image](https://user-images.githubusercontent.com/35294766/63228636-c9cdc500-c1c3-11e9-953e-88070a5895a4.png)

and here are all media downloaded that are only listed

![image](https://user-images.githubusercontent.com/35294766/63228632-b4f13180-c1c3-11e9-85a2-ee72c0d14f3f.png)


it does not list the drivers

![image](https://user-images.githubusercontent.com/35294766/63228651-e669fd00-c1c3-11e9-8e02-092ad25ac0fd.png)



so what do i do now?

**Comment by NefixEstrada** [comment]
When you create the Windows desktop, you need to mark it as a Windows install. With this, the iso is going to be added. It's explained in the docs: https://isardvdi.readthedocs.io/en/latest/install/first-steps/#win-guest

**Comment by jvinolas** [comment]
You should download Windows Virtio Drivers from updates before trying to create a Windows VM from install ISO.

**Comment by encryptblockr** [comment]
from the screenshots i have shown that the windows virtio drivers are downloaded
so not sure what else i need to show..the screenshot shows they are downloaded

![image](https://user-images.githubusercontent.com/35294766/63305043-4ee3d780-c2b3-11e9-8c4b-170f102cd1cb.png)

ok will go step by step now

![image](https://user-images.githubusercontent.com/35294766/63305068-69b64c00-c2b3-11e9-8715-df84ad8963d1.png)

then

![image](https://user-images.githubusercontent.com/35294766/63305108-92d6dc80-c2b3-11e9-97fe-7ef5e98e0bf3.png)


then still no virtio drivers show up to be added

![image](https://user-images.githubusercontent.com/35294766/63305158-c9145c00-c2b3-11e9-8fe9-b38fc6ab78ef.png)

**Comment by NefixEstrada** [comment]
Have you even tried to follow my instructions? It's quite clear what you have to do: https://github.com/isard-vdi/isard/issues/181#issuecomment-522463762

**Comment by encryptblockr** [comment]
are you telling me that from all the screenshots i have attached you can  not see that i have done everything i needed to do?

did you look at the screenshots at all?
i did everything i needed to do..everything..followed every steps in the documentation and all steps shown in screenshots

**Comment by encryptblockr** [comment]
man the documentation for windows need some work
apparently i had to click to get updates first

![image](https://user-images.githubusercontent.com/35294766/63479532-af624880-c45c-11e9-8fc7-40bd2404d8f0.png)


and then the virtio driver for windows 0 becomes available for download under "Media"

![image](https://user-images.githubusercontent.com/35294766/63479612-edf80300-c45c-11e9-83a1-76bfe7074eb3.png)


anyways got past that now and now able to add the virtio ISO driver for windows 10 but new issue arise as the documentation for windows 10 is almost non-existent
windows OS is a big part of VDI so not sure why the documentation piece for windows is so short with many points not mentioned

anyways new issue now is how to get the right driver to install windows 10

![image](https://user-images.githubusercontent.com/35294766/63479711-416a5100-c45d-11e9-8ceb-aee6e4a1cbd4.png)

![image](https://user-images.githubusercontent.com/35294766/63479735-5515b780-c45d-11e9-8bce-c40e75596c37.png)

![image](https://user-images.githubusercontent.com/35294766/63479752-6068e300-c45d-11e9-9193-f29330338db6.png)

so what driver do i pick?

![image](https://user-images.githubusercontent.com/35294766/63479775-7d9db180-c45d-11e9-9ec6-338883982427.png)

**Comment by encryptblockr** [comment]
ok finally got it thanks to the not so helpful windows documentation and had to figure this out with trial and error

![image](https://user-images.githubusercontent.com/35294766/63479883-e84eed00-c45d-11e9-8412-df0f70f77da8.png)


so anyone else having this issue..just come to this issue n windows 10 install and you can have your issue solved

![image](https://user-images.githubusercontent.com/35294766/63479940-146a6e00-c45e-11e9-82ea-ef066e806638.png)
