### ISSUE TITLE
SPICE browser keyboard issues

### ISSUE THREAD

**Issue by encryptblockr** [isard-vdi/isard#183]
There is issue with SPICE browser where i can not type `-` and instead types `/` and other symbols are off as well

![image](https://user-images.githubusercontent.com/35294766/63228953-da346e80-c1c8-11e9-9d4c-130e1b29597d.png)

VNC browser works fine though

![image](https://user-images.githubusercontent.com/35294766/63228949-c426ae00-c1c8-11e9-83f2-527389a3fa08.png)

SPICE Application works fine as well and has no issues at all

![image](https://user-images.githubusercontent.com/35294766/63228987-241d5480-c1c9-11e9-8dd3-895b03e1d365.png)

only issue is with **SPICE browser**

**Comment by jvinolas** [comment]
Could you provide us your browser language? Maybe spice javascript is setting keyboard to browser language.

**Comment by encryptblockr** [comment]
my browser is english..i mean i use the same browser for all of my browsing activities and also i showed VNC works fine as well; so am not sure it is anything to do with my browser.

**Comment by avion540** [comment]
I am also having this exact problem. The problem persists when using the SPICE Browser viewer inside Firefox or Chrome.
OS: Windows 10 version 1909
OS Language: English (no other languages configured)
Browser language: English (no other languages configured)

**Comment by NefixEstrada** [comment]
This fix will be added in the next IsardVDI version. Thanks for your feedback! :smile:
