### ISSUE TITLE
support for FreeBSD?

### ISSUE THREAD

**Issue by encryptblockr** [isard-vdi/isard#184]
Is there current support for FreeBSD desktops?
if NO, then is there plan for future support?

**Comment by NefixEstrada** [comment]
As it's written in the documentation, the only supported installation method is Docker so, if FreeBSD supports Docker, it should work as in any other platform.

If you don't want to use Docker, you can check out the different Dockerfiles and see which dependencies are needed and which configurations are needed, but we're not going to help you troubleshooting.

**Comment by sim6** [comment]
I understand that @encryptblockr asked about if FreeBSD desktops can be virtualized via IsardVDI. So, yes, IsardVDI can virtualize FreeBSD desktops.

I'm closing this issue, but please feel free to comment on it.
