### ISSUE TITLE
New builds of docker isard-app bug - CORS error

### ISSUE THREAD

**Issue by JonathanReifer** [isard-vdi/isard#191]
Can't recreate the docker images for isard-app where it will work properly with Chrome (because of CORS error)

If you attempt to build the docker images yourself and deploy with docker-compose the isard-app docker image does not work with chrome (you can login in but the page frequently disconnects)

On the server side it presents an error of "WIZARD - INFO: https://xxx.xxx.xxx.xxx is not an accepted origin"  if you enable logger.setLevel('DEBUG') in /isard/run/_webapp.py.

Within the browser (chrome) you will see that most of the /socket.io GETs and POSTs are failing with 400 BAD REQUEST.

**Comment by JonathanReifer** [comment]
Further examination indicates the following:  the problem appears when 
python-engineio module is greater then version 3.8.1 (which was what was used for the isard-app build on hub.docker.com).  Unfortunately, the python-engineio module is not pinned to that version so if you attempt to build it today it will include python-engineio ver 3.10.0 (run pip3 list from isard-app shell).

The underlying issue is that Chrome (and other browsers) are respecting cross-origin settings (CORS) and now the server side code in isard-app (with python-engineio 3.10.0) rejects the socket.io calls since either there is a mismatch between the hostname/ip of the server (because of proxy through isard-nginx to get to isard-app webserver) or because of self-signed SSL being used (by-default).

Possible solutions include:
1) pinning python-engineio version to 3.8.1 (tested - this works)
2) installing valid SSL certs (have not tested yet)

Unfortunately, attempts to configure flask-socketio to ignore cors (setting cors_allowed_origins to both '*' or '[]' )did not work.

**Comment by JonathanReifer** [comment]
Correction  - to see error message on the server, change run_webapp.py line 
engineio_logger.setLevel('ERROR) to
engineio_logger.setLevel('DEBUG').

**Comment by jvinolas** [comment]
Thanks for letting us know. Will fix it by version, not with valid certs as that would be too great a barrier for people testing Isard.
Anyway you can follow documentation and set up your valid cert before bringing up Isard. Maybe that will fix it as you proposed. Will check it also.

**Comment by jvinolas** [comment]
Pull request #195 should fix this issue in develop branch.
