### ISSUE TITLE
FailedCreatingDomain must clean hypervisor and rollback

### ISSUE THREAD

**Issue by alarraz** [isard-vdi/isard#192]
When you modify a desktop, the engine changes values to database and then it check the new configuration in a disposable hypervisor with a libvirt start-paused action. If this action fail, for example if there is not exist a bridge or capability in the hypervisor, the status of the desktop change to FailedCreatingDomain but maintain hypervisor of test in database and maintain changes in database. Better solution would be to return to original configuration, explain a message in front-end and erase hypervisor.

If you need to change the status FailedCreatingDomain to Stopped you can do this in admin view of desktops...

**Comment by jvinolas** [comment]
Do you mean not modifying the desktop in the database till then engine fully checks (start paused) the new domain configuration?
That would be nice!

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
