### ISSUE TITLE
Ldap 

### ISSUE THREAD

**Issue by ikerib** [isard-vdi/isard#196]
Hi,

We  have recently heard about this project and, it is really great!!
I created a small lab in a HP Micro Gen 8 and it is working really well, I have 4 people working for their home as they were in our town hall.
I see in the config that there is a Ldap authentication. I tried to config it but I can't and there isn't any documentation (our Ldap server is Samba)... is it working or still in development?

thanks, and great work!!

**Comment by isardvdi** [comment]
Hi!

Great to hear that you have it in production!

As for the ldap question, it is not fully integrated in web interface but you can adapt it by modifying the file: https://github.com/isard-vdi/isard/blob/master/src/webapp/config/ldapauth.py and adapting the functions setUser[Category|Group|User] on your needs.

After modifying it you will have to rebuild de isard-app container (docker-compose build isard-app) or modify the docker-compose.yml as to add the src folder to /isard with a volume. And then bring it up again.

Maybe it's better to try it in a development machine till you have tuned those functions to your ldap. Remember to activate and configure base ldap parameteres in web user interface config menu.

If it works you should be able to log in as your ldap user and category and group will be created automatically.

If you need more detailed steps please let us know. We are working in a new 2.0 release that will add many authentications.

**Comment by sim6** [comment]
Closed due to gitlab issue number conflict.

**Comment by sim6** [comment]
Please, could you try new LDAP support via [v6.0.0](https://gitlab.com/isard/isardvdi/-/releases/v6.0.0) ([!449](https://gitlab.com/isard/isardvdi/-/merge_requests/449))?

I'm closing this issue, please open new ones at [gitlab project](https://gitlab.com/isard/isardvdi/-/issues/new) if doesn't work for you.
