### ISSUE TITLE
New wired connection on ubuntu desktop

### ISSUE THREAD

**Issue by ikerib** [isard-vdi/isard#197]
Hi,
We created a Ubuntu template and 5 desktop. We have a problem because we don't know how, new wired connection is created and it losts it's configuration so the users can't access to their network files or internet. Why is that happening?

![irudia](https://user-images.githubusercontent.com/333052/78530589-3b569400-77e4-11ea-9d4c-d4d510aff7e3.png)

**Comment by jvinolas** [comment]
New desktops get new interface. This means new MAC address. Some guest OS will handle this as a new interface with no DHCP configuration by default. 

I think this is the problem. You should check that your original ubuntu template will start DHCP client on all interfaces by default, as new desktops created from that template will be identical but will see new interface.

Hope this helps.

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
