### ISSUE TITLE
cant install.. docker compose error

### ISSUE THREAD

**Issue by vpmuhsin** [isard-vdi/isard#199]
![Screenshot from 2020-04-18 19-07-42](https://user-images.githubusercontent.com/32394805/79639245-209efa80-81a8-11ea-9036-530b92653c7c.png)

ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.isard_network value Additional properties are not allowed ('name' was unexpected)

**Comment by NefixEstrada** [comment]
Which docker compose do you have? It seems a syntax error. Could you try using the one provided in the master branch?

Thanks!

**Comment by sim6** [comment]
We cannot help you with more information, please reopen the issue if you want more support.
