### ISSUE TITLE
when status change to failed from starting message must be displayed

### ISSUE THREAD

**Issue by alarraz** [isard-vdi/isard#2]
Message Desktop starting success is the last message showed as notification in web, and when the domain is failed not more message are showed
test de issue: if you rename the disk name of one domain, libvirt failed when start domain

**Comment by jvinolas** [comment]
Yes, I'm thinking about disabling de Desktop starting success message at all. When start is success (usually) now there is a modal form where you can select the viewer type. It seems useless that Desktop starting success message. What do you think?

**Comment by jvinolas** [comment]
Maybe can we show the fail message in the pop up.

**Comment by jvinolas** [comment]
#74 fixes this and a lot of other pnotify events
