### ISSUE TITLE
Format d'imatges raw i qcow

### ISSUE THREAD

**Issue by edtasixm11** [isard-vdi/isard#202]
Ampliar els tipus de formats d'imatges accessibles per generar imatges admetent raw i qcow2. Acceptades com a platilles per a generar màquines iguals.
Salut i repúplica!

**Comment by jvinolas** [comment]
Tot i que el tema formats el tenim sempre allí mai trobem temps per a posar-nos-hi. La veritat és que formats com el RAW no ens interessa utilitzar-los ja que no tenen les ventatges del format qcow2.

Sí que és veritat que ens interessa fer un sistema d'importació/exportació dels discs en diferents formats. Per importar, quants més millor. Per exportar en principi ens interessen formats tipus vmdk per utilitzar per exemple amb VirtualBox. Però sempre per a ser usats a isard en format qcow2.

La complexitat i consum de recursos que implica aquesta conversió de formats fa que no només es tracti de llançar la conversió. També cal un sistema que les programi en hores de baixa càrrega al sistema.

**Comment by sim6** [comment]
Closed due to a gitlab issue number conflict.

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
