### ISSUE TITLE
add new Interface

### ISSUE THREAD

**Issue by ikerib** [isard-vdi/isard#203]
Hi,
Our isard is working correctly but we have problems with network. Isard assings a ip range witch we want to change due to problems with 3º party network routing.

is there any way to specify the network ip range?

we tried adding a new interface but it is not working, I dive into the source and see that is not complete, maybe still working...

any help will be appreciated

**Comment by jvinolas** [comment]
Let me understand the problem better. What ip range are you talking about exactly?
IsardVDI usues an internal network between containers that is automatically assigned by docker. That may not be the problem I think, as that is an internal network.
Externally you can use any IP to acces your server. Only the viewers could be the problem but you can modify that by disabling the isard-hypervisor and editing it and reenabling it again (maybe you should do docker restart isard-webapp between those hypervisor changes)
As per the guests internet connection it will use by default a NATed network.

Could you please explain us which network is in conflict?

**Comment by ikerib** [comment]
Our Lan network range is 172.28.64.0
Internally docker assigns 172.28.0.0
Then, isard machines have 192.168.122.0
Is this last ip range we need to change to 172.29.164.0

**Comment by jvinolas** [comment]
That is strange as docker daemon should avoid network if exists. I assume that network is not in the IsardVDI server and that's the problem.

Anyway you should be able to set your desired isard_network range by setting it in docker-compose.yml file. You should edit that file and modify the networks definition at the end:

> networks:
  isard_network:
    external: false
    name: isard_network

And add your desired subnet (another one not used by your organization):

> networks:
  isard_network:
    external: false
    name: isard_network
    config:
    - subnet: 172.33.0.0/16

Note that tab spaces are not shown here but you must keep parameters tabbed in your docker-compose.yml file.

After you modified the file do a docker-compose down and docker-compose up -d and see if it worked.

You can check what ip range assigned docker by issuing: docker network inspect isard_network

**Comment by ikerib** [comment]
Thanks we'll try this afternoon

**Comment by jvinolas** [comment]
Just in case it doesn't modify the network you can down the Isard dockers, remove the network (docker network rm isard_network) and bring Isard up again. it will create the network again with new parameters.

**Comment by ikerib** [comment]
Ok!

We have peopple working on the machines now so we decided that we are going to create a new machine and try it there. If it works we will change the others

Thanks!!

**Comment by ikerib** [comment]
Hi,
I tried today with a new machine, fresh install of debian + docker and this network config on docker-compose
networks:
    isard_network:
    external: false
    name: isard_network
    ipam:
        config:
            - subnet: 172.29.164.232/29

After that I created a new ubuntu mate desktop and it is not working... it's ip is 192.168.122.65

I tried with your code but it says:
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.isard_network value Additional properties are not allowed ('config' was unexpected)

**Comment by jvinolas** [comment]
You could create the network with your defaults before bringing up isard:

> docker network create  isard_network --driver=bridge --subnet=172.18.0.0/16 --gateway=172.18.0.1 --internal=false

First look what the name is in your isardvdi install (docker network ls). You should see something like isard_network or isard_network_1 or something like that. Then, with isard down, remove that network (docker network rm isard_networ...), and create your own with the previous docke rnetwork create command (modify network/gateway as you want/need).

Then restart isard and it will take that network you already defined.

Note: To inspect the network parameters are the ones you want: docker network inspect isard_network...

**Comment by ikerib** [comment]
thanks @jvinolas with that the containers have the ip withing the subnet, but we need this IP on the desktops. I think the change has to be done withing isard rather than in docker...
It is isard which has dhcp or something and gives 192.168.122.65 to the desktop (desktop interface it is configured on dhcp not static)

thanks for all your support

**Comment by jvinolas** [comment]
I see now your problem.

That network is the default network created by libvirt inside de isard-hypervisor container. Just to be sure it works, you may try to remove default network and recreate it again with your desired IP config. These are the steps:

- Get inside de isard-hypervisor container: docker exec -ti isard-hypervisor /bin/sh
- Destroy existing default network: virsh net-destroy default
- Create new network with your desired IP config. Put inside a file the config as follows:

> cat <<EOF > mydefault.xml
<network>
  <name>default</name>
  <uuid>2696eec4-286d-4168-958b-42ef0be4ea3d</uuid>
  <bridge name="virbr0" mode="route" />
  <forward/>
  <ip address="10.1.1.1" netmask="255.255.255.0">
    <dhcp>
      <range start="10.1.1.2" end="10.1.1.254" />
    </dhcp>
  </ip>
</network>
EOF

- Create new default network from that file: virsh net-define mydefault.xml

Hope it works. Maybe config will be lost when recreating the isard-hypervisor. We will take this into account for next releases...

**Comment by ikerib** [comment]
thanks! it works, I wasn't able to destroy de default network but I edited the default network with `virsh net-edit default` and it works now. Great news!! thanks!
