### ISSUE TITLE
ISO upload fails

### ISSUE THREAD

**Issue by amelzer2020** [isard-vdi/isard#204]
Hello,
 I have created a www server with Python like the documentation suggests.
I have tested the web server where I put the iso files and It works, but IsardVDI does not download anything.
Unfortunately, in adittion to this, it cant be deleted from the media menu.

Could you take a look yo It?
Merci

**Comment by NefixEstrada** [comment]
Hello!

Could you provide more information?

What are you running? What's happening? What would you expect to happen?

Are there any relevant logs?

Thanks!

**Comment by amelzer2020** [comment]
Hello,

 I have installed the docker-compose packages on Ubuntu 18.04.
Once I go to upload media, I select http://miip:8000/myiso.iso, but It does
not start.
The progressbar does not show any progress and the upload directory, nor
the media directory dont receive the files.

If It put the isos manually Isard can not read them, so I suppose the
database should read the directories again...

The other features like updates, Desktop creation from isos that can be
downloaded from the app, they work perfect.

Thank you very much for your kind support.

Alberto Melzer Atxabal

P.S. if you prefer we can write un spanish, but as I ser that everything is
un english... Maybe you prefer in english.
I dont speak Catalán, I am from Bilbao

**Comment by amelzer2020** [comment]
Solution:
Uso python3 webserver

**Comment by antecessor** [comment]
I used `python3 -m http.server`, but have same issue. Is it possible that we copy iso files in opt/isard/media ?

**Comment by fgonzalezmacias** [comment]
I have the same problem

The ISOs are upload from direct Internet http server, as python3 server at localhost

Neither does the download start, nor does it allow to delete the download that does not start

![image](https://user-images.githubusercontent.com/72935746/96386602-69a62a80-119c-11eb-9956-cc16a472f021.png)

I
Thanks

**Comment by sim6** [comment]
Please, could you provide the Internet URL?

**Comment by fgonzalezmacias** [comment]
Yes

https://software-download.microsoft.com/pr/Win10_2004_Spanish_x64.iso?t=ea27b4af-6e3a-4aa5-a136-98a765a50782&e=1603117098&h=e30953015d7b384823f5f9988fc0108b

This link changes from time to time, but is currently operational.

I obtain the direct links to download Windows Iso, with the information of this article:

Download Windows 10 ISO directly from Microsoft without Media Creation Tool

https://www.itechtics.com/windows-10-download-iso/

Thanks in advance

**Comment by sim6** [comment]
I can download it. Do you have an hypervisor running?

**Comment by fgonzalezmacias** [comment]
Hi.
You were right. My hypervisor was not operational.
The problem was that when I re-created the VM with Ubuntu 20.04, I forgot to enable "Expose hardware-assisted virtualization to guest OS"

My virtualization system is Esxi Vmware

On the Virtual Hardware tab, expand CPU, and select Expose hardware-assisted virtualization to guest OS.

When I did it and rebooted the VM with Ubuntu 20.04 where docker is installed, the download already started and let me delete the erroneous or unfinished downloads

I'm sorry for the inconvenience, but that's how you learn ;-) and your help is incredible.

Thank you very much
