### ISSUE TITLE
does isardvdi support GPU?

### ISSUE THREAD

**Issue by encryptblockr** [isard-vdi/isard#213]
does isardvdi support GPU? what GPUs are supported and any documentation on how to set it up to use GPU?

Also is there a way to use the GPU with VMs like vGPU?

Thanks

**Comment by NefixEstrada** [comment]
Hello! We're currently working on supporting vGPUs such as NVDIA Grid or AMD's FirePro

**Comment by encryptblockr** [comment]
> Hello! We're currently working on supporting vGPUs such as NVDIA Grid or AMD's FirePro

Really nice!
How can we track work on this? Is there any current documentation?

Thanks!

**Comment by jvinolas** [comment]
Which card do you own/do you want to use? Or are you planning on using vGT?

**Comment by encryptblockr** [comment]
was planning using nvidia tesla k80 and/or tesla v100

**Comment by jvinolas** [comment]
Now we are focusing in V100 and T4, in bare metal and in cloud instances.

**Comment by sim6** [comment]
Closed due to gitlab issue number conflict.

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
