### ISSUE TITLE
Lack of direct PXE desktop creation

### ISSUE THREAD

**Issue by jvinolas** [isard-vdi/isard#23]
Although a new PXE boot desktop can be created by just using any existing desktop and changing boot to PXE, there is no clear mechanism to create a new PXE desktop. 

As it says now in documentation: You can upload any ISO file (it can be a fake file ending with .iso that you created with touch for example) and then follow the process of [creating new desktop from uploaded media](media.md#create-new-desktop-from-uploaded-media) but selecting PXE in Boot select box instead of CD/DVD.

That could lead to confusion.

**Comment by sim6** [comment]
This was closed by error due same issue id in giltab.com

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
