### ISSUE TITLE
Javascript form validators

### ISSUE THREAD

**Issue by sim6** [isard-vdi/isard#235]
There are two validators:

https://github.com/isard-vdi/isard/blob/5bf07f590d0eaaba149c0075d3b3d5b52c4756cf/webapp/webapp/webapp/templates/base.html#L103
https://github.com/isard-vdi/isard/blob/5bf07f590d0eaaba149c0075d3b3d5b52c4756cf/webapp/webapp/webapp/templates/base.html#L105

That runs simultaneously in some forms:

https://github.com/isard-vdi/isard/blob/5bf07f590d0eaaba149c0075d3b3d5b52c4756cf/webapp/webapp/webapp/templates/pages/desktops_modals.html#L220

We need to use only one.

See also: f897544fe66c824b7d2d7ce6d333a8d7d8323c79

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
