### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by Shark-Linux** [isard-vdi/isard#247]
Hello, not sure where the problem is but maybe im not the first to encounter.
![example](https://user-images.githubusercontent.com/23142357/94943353-18711800-04c7-11eb-96b6-e0c17a779e3e.png)

**Comment by sim6** [comment]
You are loosing the connection with the web server. We are working on release the version 2. So, if you are trying the IsardVDI system, please could you try the version 2.0.0-rc1?

```
wget https://raw.githubusercontent.com/isard-vdi/isard/v2.0.0-rc1/docker-compose.yml
docker-compose up
```

**Comment by Shark-Linux** [comment]
Unfortunately I dont even make it that far. Following your advice Ive not been able to get a successful build at all

`Pulling isard-db    ... done
Pulling isard-redis ... done
Creating network "isard-network" with the default driver
Building isard-api
Step 1/12 : FROM alpine:3.11.3 as production
3.11.3: Pulling from library/alpine
c9b1b535fdd9: Pull complete
Digest: sha256:ab00606a42621fb68f2ed6ad3c88be54397f981a7b70a79db3d1172b11c4367d
Status: Downloaded newer image for alpine:3.11.3
 ---> e7d92cdc71fe
Step 2/12 : MAINTAINER isard <info@isard.com>
 ---> Running in b1e1a89ab92a
Removing intermediate container b1e1a89ab92a
 ---> 56db2f389167
Step 3/12 : RUN apk add python3
 ---> Running in 36558ffd0d4e
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/10) Installing libbz2 (1.0.8-r1)
(2/10) Installing expat (2.2.9-r1)
(3/10) Installing libffi (3.2.1-r6)
(4/10) Installing gdbm (1.13-r1)
(5/10) Installing xz-libs (5.2.4-r0)
(6/10) Installing ncurses-terminfo-base (6.1_p20200118-r4)
(7/10) Installing ncurses-libs (6.1_p20200118-r4)
(8/10) Installing readline (8.0.1-r0)
(9/10) Installing sqlite-libs (3.30.1-r2)
(10/10) Installing python3 (3.8.2-r1)
Executing busybox-1.31.1-r9.trigger
OK: 64 MiB in 24 packages
Removing intermediate container 36558ffd0d4e
 ---> cfc386cf43e4
Step 4/12 : RUN pip3 install --upgrade pip
 ---> Running in ce9241f7c852
Collecting pip
  Downloading https://files.pythonhosted.org/packages/4e/5f/528232275f6509b1fff703c9280e58951a81abe24640905de621c9f81839/pip-20.2.3-py2.py3-none-any.whl (1.5MB)
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-20.2.3
Removing intermediate container ce9241f7c852
 ---> 7050e2cc3e6f
Step 5/12 : RUN apk add --no-cache --virtual .build_deps     build-base     python3-dev     libffi-dev
 ---> Running in 4ba8af7c1c21
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/24) Upgrading musl (1.1.24-r0 -> 1.1.24-r2)
(2/24) Installing libgcc (9.3.0-r0)
(3/24) Installing libstdc++ (9.3.0-r0)
(4/24) Installing binutils (2.33.1-r0)
(5/24) Installing libmagic (5.37-r1)
(6/24) Installing file (5.37-r1)
(7/24) Installing gmp (6.1.2-r1)
(8/24) Installing isl (0.18-r0)
(9/24) Installing libgomp (9.3.0-r0)
(10/24) Installing libatomic (9.3.0-r0)
(11/24) Installing mpfr4 (4.0.2-r1)
(12/24) Installing mpc1 (1.1.0-r1)
(13/24) Installing gcc (9.3.0-r0)
(14/24) Installing musl-dev (1.1.24-r2)
(15/24) Installing libc-dev (0.7.2-r0)
(16/24) Installing g++ (9.3.0-r0)
(17/24) Installing make (4.2.1-r2)
(18/24) Installing fortify-headers (1.1-r0)
(19/24) Installing build-base (0.5-r1)
(20/24) Installing pkgconf (1.6.3-r0)
(21/24) Installing python3-dev (3.8.2-r1)
(22/24) Installing linux-headers (4.19.36-r0)
(23/24) Installing libffi-dev (3.2.1-r6)
(24/24) Installing .build_deps (20201003.014634)
Executing busybox-1.31.1-r9.trigger
OK: 288 MiB in 47 packages
Removing intermediate container 4ba8af7c1c21
 ---> 76ed882bf5e9
Step 6/12 : COPY api/docker/requirements.pip3 /requirements.pip3
 ---> a45d8b13f7f9
Step 7/12 : RUN pip3 install --no-cache-dir -r requirements.pip3
 ---> Running in 350f422190de
Collecting bcrypt==3.1.7
  Downloading bcrypt-3.1.7.tar.gz (42 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting cffi==1.14.0
  Downloading cffi-1.14.0.tar.gz (463 kB)
Collecting click==7.1.2
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting Flask==1.1.2
  Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting Flask-Login==0.5.0
  Downloading Flask_Login-0.5.0-py2.py3-none-any.whl (16 kB)
Collecting gevent==20.6.0
  Downloading gevent-20.6.0.tar.gz (5.8 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting greenlet==0.4.16
  Downloading greenlet-0.4.16.tar.gz (60 kB)
Collecting itsdangerous==1.1.0
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Jinja2==2.11.2
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting MarkupSafe==1.1.1
  Downloading MarkupSafe-1.1.1.tar.gz (19 kB)
Collecting pycparser==2.20
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting rethinkdb==2.4.7
  Downloading rethinkdb-2.4.7-py2.py3-none-any.whl (156 kB)
Collecting six==1.15.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting Werkzeug==1.0.1
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting zope.event==4.4
  Downloading zope.event-4.4-py2.py3-none-any.whl (7.6 kB)
Collecting zope.interface==5.1.0
  Downloading zope.interface-5.1.0.tar.gz (225 kB)
Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (from gevent==20.6.0->-r requirements.pip3 (line 6)) (41.2.0)
Using legacy 'setup.py install' for cffi, since package 'wheel' is not installed.
Using legacy 'setup.py install' for greenlet, since package 'wheel' is not installed.
Using legacy 'setup.py install' for MarkupSafe, since package 'wheel' is not installed.
Using legacy 'setup.py install' for zope.interface, since package 'wheel' is not installed.
Building wheels for collected packages: bcrypt, gevent
  Building wheel for bcrypt (PEP 517): started
  Building wheel for bcrypt (PEP 517): finished with status 'done'
  Created wheel for bcrypt: filename=bcrypt-3.1.7-cp38-cp38-linux_x86_64.whl size=60842 sha256=45a4539011a78b09517c195e56a2a5f15dc5c9ce201b39db6322add7f223e3de
  Stored in directory: /tmp/pip-ephem-wheel-cache-2sqsezld/wheels/08/dd/04/63fe9a4002c36105c358f90221e4882825a264edb9d8554163
  Building wheel for gevent (PEP 517): started
  Building wheel for gevent (PEP 517): still running...
  Building wheel for gevent (PEP 517): finished with status 'done'
  Created wheel for gevent: filename=gevent-20.6.0-cp38-cp38-linux_x86_64.whl size=4069276 sha256=69461f624175a016bc3b820059331dc8b97b31a3d9ec9f333113b1d61c93147b
  Stored in directory: /tmp/pip-ephem-wheel-cache-2sqsezld/wheels/11/18/15/4da2560dfb7fe13a585d8a9e8099eb58c58dc4f83732515c91
Successfully built bcrypt gevent
Installing collected packages: pycparser, cffi, six, bcrypt, click, Werkzeug, MarkupSafe, Jinja2, itsdangerous, Flask, Flask-Login, zope.interface, greenlet, zope.event, gevent, rethinkdb
    Running setup.py install for cffi: started
    Running setup.py install for cffi: finished with status 'done'
    Running setup.py install for MarkupSafe: started
    Running setup.py install for MarkupSafe: finished with status 'done'
    Running setup.py install for zope.interface: started
    Running setup.py install for zope.interface: finished with status 'done'
    Running setup.py install for greenlet: started
    Running setup.py install for greenlet: finished with status 'done'
Successfully installed Flask-1.1.2 Flask-Login-0.5.0 Jinja2-2.11.2 MarkupSafe-1.1.1 Werkzeug-1.0.1 bcrypt-3.1.7 cffi-1.14.0 click-7.1.2 gevent-20.6.0 greenlet-0.4.16 itsdangerous-1.1.0 pycparser-2.20 rethinkdb-2.4.7 six-1.15.0 zope.event-4.4 zope.interface-5.1.0
Removing intermediate container 350f422190de
 ---> 79235a862f98
Step 8/12 : RUN apk del .build_deps
 ---> Running in 71a543dd55cd
(1/23) Purging .build_deps (20201003.014634)
(2/23) Purging build-base (0.5-r1)
(3/23) Purging file (5.37-r1)
(4/23) Purging g++ (9.3.0-r0)
(5/23) Purging gcc (9.3.0-r0)
(6/23) Purging binutils (2.33.1-r0)
(7/23) Purging libatomic (9.3.0-r0)
(8/23) Purging libgomp (9.3.0-r0)
(9/23) Purging libstdc++ (9.3.0-r0)
(10/23) Purging make (4.2.1-r2)
(11/23) Purging libc-dev (0.7.2-r0)
(12/23) Purging musl-dev (1.1.24-r2)
(13/23) Purging fortify-headers (1.1-r0)
(14/23) Purging python3-dev (3.8.2-r1)
(15/23) Purging libffi-dev (3.2.1-r6)
(16/23) Purging linux-headers (4.19.36-r0)
(17/23) Purging libgcc (9.3.0-r0)
(18/23) Purging libmagic (5.37-r1)
(19/23) Purging isl (0.18-r0)
(20/23) Purging mpc1 (1.1.0-r1)
(21/23) Purging mpfr4 (4.0.2-r1)
(22/23) Purging gmp (6.1.2-r1)
(23/23) Purging pkgconf (1.6.3-r0)
Executing busybox-1.31.1-r9.trigger
OK: 64 MiB in 24 packages
Removing intermediate container 71a543dd55cd
 ---> aed3b5aa2fbe
Step 9/12 : RUN apk add curl
 ---> Running in 7cd9febe49a9
(1/4) Installing ca-certificates (20191127-r2)
(2/4) Installing nghttp2-libs (1.40.0-r1)
(3/4) Installing libcurl (7.67.0-r1)
(4/4) Installing curl (7.67.0-r1)
Executing busybox-1.31.1-r9.trigger
Executing ca-certificates-20191127-r2.trigger
OK: 66 MiB in 28 packages
Removing intermediate container 7cd9febe49a9
 ---> dfd5d2e49aca
Step 10/12 : COPY api/src /api
 ---> faf0bce3882c
Step 11/12 : WORKDIR /api
 ---> Running in 9810d9512519
Removing intermediate container 9810d9512519
 ---> 5714c1f6dbb5
Step 12/12 : CMD [ "python3", "start.py" ]
 ---> Running in 3739d273a02d
Removing intermediate container 3739d273a02d
 ---> 49cd95caef60

Successfully built 49cd95caef60
Successfully tagged isard/api:2.0.0-rc1
WARNING: Image for service isard-api was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building isard-backend
Step 1/10 : FROM golang:1.14-alpine as build
1.14-alpine: Pulling from library/golang
df20fa9351a1: Already exists
ed8968b2872e: Pull complete
a92cc7c5fd73: Pull complete
5d0547b08c89: Pull complete
d5b6f0657434: Pull complete
Digest: sha256:050b2322a11b7e6fbde31a9c95b3b090297a47beedaf992da787ee84b3c35ad6
Status: Downloaded newer image for golang:1.14-alpine
 ---> 0223ac8ea40d
Step 2/10 : RUN apk add --no-cache 	make
 ---> Running in 609db1c86cc6
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/1) Installing make (4.3-r0)
Executing busybox-1.31.1-r16.trigger
OK: 6 MiB in 16 packages
Removing intermediate container 609db1c86cc6
 ---> a24d60c8c0f0
Step 3/10 : COPY . /go/src/github.com/isard-vdi/isard/backend
 ---> 6361908a0875
Step 4/10 : WORKDIR /go/src/github.com/isard-vdi/isard/backend
 ---> Running in 99c40ba97251
Removing intermediate container 99c40ba97251
 ---> 1df6e589abf0
Step 5/10 : RUN make build
 ---> Running in 3ad014d66d55
go build -o backend cmd/backend/*.go
go: downloading github.com/spf13/afero v1.3.2
go: downloading go.uber.org/zap v1.15.0
go: downloading github.com/crewjam/saml v0.4.0
go: downloading github.com/go-redis/redis v6.15.8+incompatible
go: downloading github.com/rbcervilla/redisstore v1.1.0
go: downloading github.com/gorilla/sessions v1.2.0
go: downloading github.com/gorilla/mux v1.7.4
go: downloading golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
go: downloading github.com/gorilla/securecookie v1.1.1
go: downloading github.com/segmentio/ksuid v1.0.3
go: downloading golang.org/x/text v0.3.0
go: downloading cloud.google.com/go v0.34.0
go: downloading golang.org/x/net v0.0.0-20190620200207-3b0461eec859
go: downloading github.com/nefixestrada/pongo v1.0.0
go: downloading github.com/beevik/etree v1.1.0
go: downloading github.com/russellhaering/goxmldsig v0.0.0-20180430223755-7acd5e4a6ef7
go: downloading github.com/crewjam/httperr v0.0.0-20190612203328-a946449404da
go: downloading go.uber.org/atomic v1.6.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading go.uber.org/multierr v1.5.0
go: downloading golang.org/x/crypto v0.0.0-20190923035154-9ee001bba392
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/jonboulle/clockwork v0.1.0
Removing intermediate container 3ad014d66d55
 ---> 120d235afdd8

Step 6/10 : FROM alpine:3.11.3
 ---> e7d92cdc71fe
Step 7/10 : MAINTAINER isard <info@isard.com>
 ---> Using cache
 ---> 56db2f389167
Step 8/10 : COPY --from=build /go/src/github.com/isard-vdi/isard/backend /
 ---> 3bae20053a69
Step 9/10 : EXPOSE 8080
 ---> Running in d7b54befe258
Removing intermediate container d7b54befe258
 ---> 63e95f9cd39f
Step 10/10 : CMD [ "/backend" ]
 ---> Running in d6d7adb04605
Removing intermediate container d6d7adb04605
 ---> fe890e29f95d

Successfully built fe890e29f95d
Successfully tagged isard/backend:2.0.0-rc1
WARNING: Image for service isard-backend was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building isard-engine
Step 1/17 : FROM alpine:3.11.3 as production
 ---> e7d92cdc71fe
Step 2/17 : MAINTAINER isard <info@isard.com>
 ---> Using cache
 ---> 56db2f389167
Step 3/17 : RUN apk add --no-cache     yarn     py3-libvirt==5.9.0-r0     py3-paramiko==2.7.1-r0     py3-lxml==4.4.2-r0     py3-openssl==19.1.0-r0     py3-bcrypt==3.1.7-r2     py3-gevent==1.4.0-r2     py3-flask==1.0.4-r0     py3-netaddr==0.7.19-r4     py3-requests==2.22.0-r0     py3-numpy==1.17.4-r1     py3-pyldap==3.2.0-r1     libvirt-client==5.9.0-r1     curl==7.67.0-r0     openssh-client==8.1_p1-r0     sshpass==1.06-r0     supervisor==4.1.0-r0
 ---> Running in 3a8598505d3f
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  curl-7.67.0-r1:
    breaks: world[curl=7.67.0-r0]
  libvirt-client-5.9.0-r2:
    breaks: world[libvirt-client=5.9.0-r1]
ERROR: Service 'isard-engine' failed to build: The command '/bin/sh -c apk add --no-cache     yarn     py3-libvirt==5.9.0-r0     py3-paramiko==2.7.1-r0     py3-lxml==4.4.2-r0     py3-openssl==19.1.0-r0     py3-bcrypt==3.1.7-r2     py3-gevent==1.4.0-r2     py3-flask==1.0.4-r0     py3-netaddr==0.7.19-r4     py3-requests==2.22.0-r0     py3-numpy==1.17.4-r1     py3-pyldap==3.2.0-r1     libvirt-client==5.9.0-r1     curl==7.67.0-r0     openssh-client==8.1_p1-r0     sshpass==1.06-r0     supervisor==4.1.0-r0' returned a non-zero code: 2
`

**Comment by sim6** [comment]
If you want to build the images you need to clone the repository and run ./build.sh script. But if you want to pull the images you can do `docker-compose pull` but you need a docker-compose version greater or equal to 1.25.1. You can get recent versions of it via `pip install docker-compose`.

**Comment by sim6** [comment]
Please, could you maintain us up to date about your progress?

**Comment by sim6** [comment]
I'm closing this issue due to lack of feedback but, please, feel free to add more comments if you want more support.
