### ISSUE TITLE
docker-compose doesn't work without source code

### ISSUE THREAD

**Issue by sim6** [isard-vdi/isard#248]
Error when following the instructions from README.md using develop branch instead of master:

```
% cd /tmp
% wget https://raw.githubusercontent.com/isard-vdi/isard/develop/docker-compose.yml.example
% docker-compose -f docker-compose.yml.example pull
ERROR: build path /tmp/backend either does not exist, is not accessible, or is not a valid URL.
% docker-compose --version
docker-compose version 1.25.0, build unknown
```

Running `docker-compose pull` from versions <= 1.25.0 doesn't try to pull images of services that have build section (https://github.com/docker/compose/blob/1.25.0/compose/project.py#L622). Newer versions >= 1.25.1 tries to download it before building (https://github.com/docker/compose/blob/1.25.1/compose/project.py#L633).

Recent versions of docker-compose can be get via `pip install docker-compose`.

Unfortunately Debian brings with 1.25.0. So, should we provide a docker-compose.yml without build section to make it easy for puller users?

See also #247

**Comment by NefixEstrada** [comment]
I'm not really sure how we should proceed. The `docker-compose.yml` file is automatically generated by the `build.sh` script, that uses the yaml files inside the `yml` directory. If we want to provide separate compose files, we should edit those. Maybe we should separate the build parameters in separate yaml files? And then in the `build.sh` script add different parameters that call different yaml files?

What do you think?

**Comment by sim6** [comment]
I opened this issue to document the problem and start a discussion. We can do nothing and say that the problem is due to a lack of Debian update, but this doesn't fix the problem.
Currently, in develop branch `build.sh` can be run in 3 ways:
1. Without parameters to create:
  - docker-compose.yml
  - docker-compose.yml.devel
2. With `hypervisor` parameter to create:
  - hypervisor.yml
  - devel-hypervisor.yml
3. With `web` paramerter to create:
  - web.yml
  - devel-web.yml

We can always build all `docker-compose.yml` flavor files but with an appropriate names like:

docker-compose.yml
docker-compose.build.yml
docker-compose.build.devel.yml
docker-compose.hypervisor.yml
docker-compose.hypervisor.build.yml
docker-compose.hypervisor.build.devel.yml
docker-compose.web.yml
docker-compose.web.build.yml
docker-compose.web.build.devel.yml

**Comment by sim6** [comment]
Not only docker-compose <= 1.25.0 tries to build the images, see  #265.

**Comment by sim6** [comment]
https://github.com/docker/compose/issues/7873

**Comment by fgarpe** [comment]
Hi, the same issue here following the install guide at https://isardvdi.readthedocs.io/en/develop/install/install/

**Comment by fgarpe** [comment]
docker-compose up --no-build -d seems like solve this issue

https://github.com/docker/compose/issues/3391

**Comment by fgarpe** [comment]
doesn't solve the issue... with --no-build option I can create and start the container, but I can't do others operations like restart :(

**Comment by sim6** [comment]
Thank you anyway.

**Comment by sim6** [comment]
This is blocked by #284

**Comment by jvinolas** [comment]
I understand the problem here, but we do really need the hypervisor without video and I will need also a video without hypervisor (I will fill pull request maybe tomorrow).
We do really need those two extra compose files for infrastructure implementations (hypervisor-novideo and video). Maybe we could name them standalone-hypervisor and video.

**Comment by sim6** [comment]
@jvinolas I understand that you mean that we need #284 to generate these extra docker-compose.yml, but we need to generate one without build section and other with build section. I propose merge first #284 and then work with a new build version that generate all docker-compose files with a proper name.

**Comment by sim6** [comment]
Ok, I understand it now, we need this #305.
