### ISSUE TITLE
Use black formatter

### ISSUE THREAD

**Issue by NefixEstrada** [isard-vdi/isard#251]
Currently, the code of Isard doesn't follow any coding style standards. This may introduce new bugs and make contributions harder for new contributions.

[Black](https://github.com/psf/black) is a code formatter that is very strict, making all the code look the same. Also, since it's a formatter, you can code as you want and run the formatter afterwards and it doesn't bother you while you're coding

What do you think?

**Comment by sim6** [comment]
Are you thinking about make a mega change at some point that doesn't break so much works in progress?

**Comment by sim6** [comment]
Done via https://gitlab.com/isard/isardvdi/-/merge_requests/424
