### ISSUE TITLE
Wizard never starts

### ISSUE THREAD

**Issue by squallm3** [isard-vdi/isard#254]
Hi!
I've installed Isard on a Fedora 32 over docker.
I've changed cgroups to v1 to get docker work.
After that installed Isard. It seems pretty straightforward.
The problem is that when i'm trying to access the web page i see the logo and the legend: 
_"It seems that the application is getting started...

Please wait. The page is going to refresh automatically. If this page appears too much time, contact your IsardVDI administrator or check the logs"_

The page keeps refreshing but never goes forward.
In the logs i can see this several times: 

_2020/10/10 11:02:06 - WIZARD - WARNING: Starting initial configuration wizard
2020/10/10 11:02:06 - WIZARD - INFO: ISARD WEBCONFIG STARTED: Access on http://localhost:5000 or https://localhost on dockers.
2020/10/10 11:02:06 - WIZARD - INFO:  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)_

I tried reinstalling Isard but nothing happen.
Anyone can help me with this?

Thanks in advance!

**Comment by sim6** [comment]
Hello,
Thanks to try IsardVDI. We are working to release the v2. Please, could you try the v2.0.0-rc1?

```
wget https://raw.githubusercontent.com/isard-vdi/isard/v2.0.0-rc1/docker-compose.yml
docker-compose pull && docker-compose up
```

https://isardvdi.readthedocs.io/en/develop/

**Comment by squallm3** [comment]
Hi!
Thanks for the fast answer!
I'm still having the same problem but now i can see this problem in the cmd after installig:

_isard-nginx         | 2020/10/11 12:15:53 [error] 9#9: *266 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.1.144, server: isard.localdomain, request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:5000/", host: "192.168.1.124"_

I saw that some people have the "no route to host problem" with Nginx and they solve it adding a firewall rule. I did it but didn't work it.

Maybe the problem is the combination Os + App? I can try another os.

Thanks!

**Comment by sim6** [comment]
Thanks for keep us updated about your progress.

isard-nginx is a container name used in IsarvVDI v1 but not in v2.

Please could you try to download the docker-compose.yml of v2.0.0-rc1 from 
https://raw.githubusercontent.com/isard-vdi/isard/v2.0.0-rc1/docker-compose.yml

Thanks.

**Comment by squallm3** [comment]
Thanks again for the answer!
Finally, I installed Linux Mint and it worked like a charm.
Thank you for the support!

**Comment by sim6** [comment]
Anyway, please use the v2.
