### ISSUE TITLE
Problem deleting iso file not up sucessfully

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#265]
Hello.

When I try to up a iso file from http, and I obtain an error, I can`t delete the description of the iso file. After of to try delete, the message is "deleting"

Thanks in advance

![IsardVDI_Deleting](https://user-images.githubusercontent.com/72935746/96156570-8418a380-0f11-11eb-83d8-c1ae2b0af2da.png)

**Comment by sim6** [comment]
Thanks for reporting we will take care.

**Comment by sim6** [comment]
Duplicated #180

We are working to release the v2, please could you try it.
```
rm -r /opt/isard
wget https://raw.githubusercontent.com/isard-vdi/isard/v2.0.0-rc1/docker-compose.yml
docker-compose pull && docker-compose up
```
Thanks again.

**Comment by fgonzalezmacias** [comment]
Ok. I install the v2.0.0-rc1 versión and I have to create two folders: backend and websockify. I go to the web https://localhost and I obtain a new login page

![image](https://user-images.githubusercontent.com/72935746/96237698-e7e8ae00-0f9d-11eb-8c5c-d804dd5ee554.png)

I try with admin and isardvdi, but no sucessfully. I don`t have the configuration process where ask for the password, etc...

Thanks in advance

PD: I'm spanish. Exist any preferred or mandatory language to made the comments?. It's english the default option?

**Comment by sim6** [comment]
If you prefer you can use Spanish, no problem. Seems that you are using a old version of docker-compose, that doesn't pull the docker images and build it, please see #248. About the default user and password see the new documentation at https://isardvdi.readthedocs.io/en/develop/

Thanks, and please, keep us updated about your progress.

**Comment by fgonzalezmacias** [comment]
Hola.  Finalmente pude logonearme, en el panel de administración https://localhost/isard-admin con el usuario y password, por defecto -admin/IsardVDI-

Comentar que al intentar subir de nuevo algún ISO, se quedó en StartDownloading y no existe icono a la derecha sobre el que actuar.

Eliminé la instalación y la volví a implementar.

Tengo otro problema, pero entiendo que ya debo abrir otro caso. Muchas gracias, por este magnífico proyecto. He visto todos los videos de Rediris y demás y os doy la enhorabuena.

**Comment by fgonzalezmacias** [comment]
Respecto a lo que comenté que tuve que crear las carpetas backend y websockify a la hora de realizar el docker-compose up -d
pues daba error, como se puede ver en la imagen adjunta. Tras crearla ya funcionó correctamente el docker-compose up -d

La versión de docker-compose es la 1.27.4, creo que está actualizada

![image](https://user-images.githubusercontent.com/72935746/96280102-dfad6480-0fd7-11eb-9f10-0837399fbd46.png)

Gracias

**Comment by sim6** [comment]
No tienes que crear estas carpetas. El `ERROR: build path` significa que esta intentando generar las imágenes de docker. Si creas carpetas vacías las imagenes de docker no tendrán el código que tienen que tener. Si quieres generar la imágenes tienes que clonar el repositorio. Pero, no hace falta que las generes, puedes descargarte las imágenes.

Ejecutando el comando `docker-compose pull` deberías obtener todas las imágenes necesarias. Puedes comprobar que tienes las imágenes correctas de isard/backend y isard/websockify comparando el checksum de los siguientes comandos con los de hub.docker.com:

https://hub.docker.com/r/isard/backend/tags
```
docker images --digests isard/backend
```

https://hub.docker.com/r/isard/websockify/tags
```
docker images --digests isard/websockify  
```

Si docker-compose no te las descarga correctamente, puedes modificar el docker-compose.yml borrando las secciones `build` como esta:
https://github.com/isard-vdi/isard/blob/b3e5a05b82437637688bc268d333941f4cf4b61f/docker-compose.yml#L61-L63

**Comment by fgonzalezmacias** [comment]
Hola. Como no solventaba el tema y estaba en pruebas. He eliminado la VM que alojaba la Ubuntu 20.04 Server y donde tenía instalado docker y la he eliminado y vuelto a crear, instalando desde cero Ubuntu 20.04 e instalando docker y docker-compose siguiendo instrucciones de:

https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04-es
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-20-04-es

Hasta aquí todo ok

El caso es que estoy logoneado con una cuenta administrador, y estoy situado en mi /home/administrador/
Aquí ejecuto:

#wget https://raw.githubusercontent.com/isard-vdi/isard/v2.0.0-rc1/docker-compose.yml
#docker-compose pull

Hasta aquí todo correcto, pero cuando ya ejecuto el docker-compose up -d, obtengo el error de la imagen.

![image](https://user-images.githubusercontent.com/72935746/96352407-32b01600-10c3-11eb-83cb-71383a29577b.png)


En algún artículo sobre IsardVDI, he visto que comentaban, el crear la carpeta /opt/IsardVDI y dentro de ella realizar el wget, y los dos comandos docker-compose

Esto también lo probé, pero con el mismo resultado y obteniendo el mismo error.

Probé también lo de eliminar la sección build de las secciones backens y websockify, Con esto ya se ejecuta el docker-compose up -d sin error, pero después seguía teniendo el mismo problema a la hora de crear el Desktop desde la imagen ISO subida

¿Alguna idea de por donde puede venir mi error?

Gracias

**Comment by sim6** [comment]
Gracias por mantenernos informados. Me alegro que sin las secciones `build` te funcione. Tendremos que crear un docker-compose.yml sin las secciones `build` (#248). Referente a crear un escritorio desde el apartado Media, por favor lee https://github.com/isard-vdi/isard/issues/270#issuecomment-711091766.

**Comment by sim6** [comment]
Por favor, puedes borrar todas las secciones `build` del docker-compose.yml, no solo las referentes a isard-backend y isard-websockify.

**Comment by fgonzalezmacias** [comment]
Hola. He realizado un docker system prune -a y un rm  -* en ./opt/

He descargado el docker-compose.yml y eliminado todas las secciones build de los distintos contenedores.

En principio ok, no he notado diferencia con eliminarlo sólo de las referencias isard-backend e isard-websockify

¿Es porque querías que probara algo, o porque es incorrecto eliminar la sección build de esos dos contenedores del docker-compose.yml?

Gracias

**Comment by sim6** [comment]
Perdón, me confundí, es con la versión 1.25.0 de docker-compose que hay que borrar todas las secciones `build` para poder arrancar sin el código fuente.

**Comment by fgonzalezmacias** [comment]
Ningún problema. Muchísimas gracias por toda tu ayuda en el arranque con IsardVDI. Un abrazo
