### ISSUE TITLE
No funciona la creación de Desktop a partir de imagen ISO

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#270]
Hola. He subido una  ISO, de Windows 10 e intento crear un Desktop a partir de dicha imagen. El caso es que configuro el Desktop, y cuando le doy al botón de "Create Desktop", no hace absolutamente nada

Gracias

![image](https://user-images.githubusercontent.com/72935746/96280650-83971000-0fd8-11eb-9a95-7f5d7dfc0213.png)

**Comment by sim6** [comment]
Necesitamos que el sistema funcione, por favor, puedes seguir las instrucciones de https://github.com/isard-vdi/isard/issues/265#issuecomment-710238072.

**Comment by sim6** [comment]
Por favor, usa la sección Media que no esta dentro del menú Administrator ya que esta tiene un error corregido con #275 pero que todavía no tienes en tu sistema.

**Comment by fgonzalezmacias** [comment]
Efectivamente en la sección Media dentro de Domains, no me deja crear el Desktop, sin embargo sí, desde la sección Media asociada al user, en la parte superior.
Esto veo que ya lo tenéis controlado. Muchas gracias
