### ISSUE TITLE
File console.vv change proxy=http://localhost:80 to proxy=http://ip-server:80

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#277]
This value makes sense, if the configuration is done from the docker server itself, but not if it is done externally, as usual
```
[virt-viewer]
        type=spice
        proxy=http://localhost:80
        host=isard-hypervisor
        password=8zymdwnT9zp2XYwzGx1WqilU0LwQdre4
        tls-port=5901
        fullscreen=0
        title=Windows 10 20_04 Redactor (TLS):%d - Prem SHIFT+F12 per sortir
        enable-smartcard=0
        enable-usb-autoshare=1
        delete-this-file=1
        usb-filter=-1,-1,-1,-1,0
        tls-ciphers=DEFAULT
        host-subject=CN=*.localdomain
       
        toggle-fullscreen=shift+f11
        release-cursor=shift+f12
        secure-attention=ctrl+alt+end
        secure-channels=main;inputs;cursor;playback;record;display;usbredir;smartcard
```

**Comment by sim6** [comment]
You need to change HOSTNAME variables in docker-compose.yml.

Also you create your docker-compose.yml doing a clone of the repository, then create an isardvdi.cfg with the apropiate HOSTNAME value (you can copy the contents of isardvdi.cfg.example) and then build.sh.

**Comment by sim6** [comment]
To change it you need to follow the next instructions:
* Login in admin site as admin role.
* Go to "Hypervisors" section.
* Click on plus button of an hypervisor.
* Click on "Enable/Disable" button to disable the hypervisor.
* Click on "Ok" button to confirm the dialog.
* Click on "Edit" button.
* Change "Video proxy host (squid/websockify)" value with the external IP or domain.
* Click on "Update hypervisor" button.
* Click on "Enable/Disable" button to enable the hypervisor.
* Click on "Ok" button to confirm the dialog.
* Restart isard-engine running `docker-compose restart isard-engine` (this is due a current bug in v2.0.0-rc1)

**Comment by fgonzalezmacias** [comment]
I update the fields, with your information.

Thanks
