### ISSUE TITLE
Button create Category

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#278]
the create Category button does nothing

![image](https://user-images.githubusercontent.com/72935746/96476754-e802db00-1235-11eb-95aa-5cbc51d3bde4.png)

**Comment by sim6** [comment]
Please, could you avoid accent marks until we update socket.io (#263)?

**Comment by fgonzalezmacias** [comment]
Correct. The problem is by the accent mark.

Thanks

**Comment by fgonzalezmacias** [comment]
One question please.

is this fix now available? 

I made now docker-compose stop
docker system prune -a

Then docker-compose pull & docker-compose up -d

But I haven`t this fix applied

thanks in advance

**Comment by sim6** [comment]
Maybe you are using a docker-compose.yml of version 2.0.0-rc1. This fix is available in `develop` version.
You can switch to `develop` version following the next instructions:
```
docker-compose up -d
docker cp isard-hypervisor:/etc/ssh ssh
docker-compose stop
wget -qO - https://isardvdi.com/docker-compose.yml | sed -e 's/v2.0.0-rc1/develop/' -e '/^    build:/d' -e '/^      \(context\|dockerfile\):/d' -e '/^      target: production$/d' > docker-compose.yml
docker-compose pull
docker-compose up -d
docker cp ssh isard-hypervisor:/etc/
docker run isard-hypervisor chown -R qemu /etc/pki/libvirt-spice
```

**Comment by fgonzalezmacias** [comment]
Applied, but with the las line of the script, I obtain the next error:

administrador@cadi16:/opt/IsardVDI$ sudo docker run isard-hypervisor chown -R qemu /etc/pki/libvirt-spice
Unable to find image 'isard-hypervisor:latest' locally
docker: Error response from daemon: pull access denied for isard-hypervisor, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by fgonzalezmacias** [comment]
Also I have one desktop created, and now I don't can to start

![image](https://user-images.githubusercontent.com/72935746/97171219-5fcc8a80-178d-11eb-8d4e-46f5b16d4d3f.png)

I'm in the developer version, because I can already create accented categories

Thanks in advance

**Comment by sim6** [comment]
I'm sorry. the last line of https://github.com/isard-vdi/isard/issues/278#issuecomment-716102809 sould be the following
```
docker-compose  run isard-hypervisor chown -R qemu /etc/pki/libvirt-spice
```
It sould solve the problem described in https://github.com/isard-vdi/isard/issues/278#issuecomment-716509692

**Comment by fgonzalezmacias** [comment]
Indeed, I was able to start my Desktop correctly.

If I wanted to update my local installation from time to time, with the updates being saved in the developer branch, would I run the same script? or,  would the following commands be enough?

docker-compose stop
docker-compose pull
docker-compose up -d

Thanks

**Comment by sim6** [comment]
We are working on it but meanwhile you need to run extra commands. Eg. #290

**Comment by fgonzalezmacias** [comment]
Ok, Thanks
