### ISSUE TITLE
Desktop VM is not up when I change value webhost at hypervisor configuration

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#279]
![image](https://user-images.githubusercontent.com/72935746/96620459-c2460680-1307-11eb-9f73-5633f2948522.png)

![image](https://user-images.githubusercontent.com/72935746/96620910-4d270100-1308-11eb-8ddb-df2b9825e616.png)

I read the documentation and I try to change the value webhost to the local ip of the isard host. 

I did the sudo docker-compose restart isard-engine, and the hypervisor is ok, but the circle is continually spinning

I try to reboot the host and the result is the same.

Thanks in advance.

**Comment by sim6** [comment]
Yes, there is a bug that breaks isard-engine when hypervisors changes. But I can recover the system restarting isard-engine.

**Comment by fgonzalezmacias** [comment]
Hello. 

Logs?

#docker-compose logs?

**Comment by sim6** [comment]
Also /opt/isard-local/logs

**Comment by fgonzalezmacias** [comment]
The Desktop I could recover it through Global Action -> Force Stop, but the Template is with the circle spinning.

I did the docker-compose restart isard-engine, but the same.

![image](https://user-images.githubusercontent.com/72935746/96729123-1b1fa880-13b5-11eb-8c27-d126151f6e68.png)

**Comment by fgonzalezmacias** [comment]
[Isard-local.zip](https://github.com/isard-vdi/isard/files/5416522/Isard-local.zip)

I attach the logs inside /opt/isard-local/logs/engine and /opt/isard-local/logs/webapp

**Comment by sim6** [comment]
Your database is down. Please, could you restart it via `docker-compose restart isard-db`?

**Comment by fgonzalezmacias** [comment]
Previously I executed that command, because I have problem to validate login at http://localhost/

But I understand that the BD is up if i can see the Administrator Users and others users not showed

![image](https://user-images.githubusercontent.com/72935746/96735711-21fde980-13bc-11eb-96e8-2fd357e3fe99.png)


Anyway I have run the docker-compose restart isard-db again, and with the same result

thanks

**Comment by jvinolas** [comment]
Does restarting the whole dockers solve the problem?

**Comment by fgonzalezmacias** [comment]
No. I finally did a new installation. Thanks
