### ISSUE TITLE
Change disk size of a Desktop

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#285]
I don't see how to change the disk size of a Desktop, after it's created.

I think must be possible to change, to increase this initial value of GBs.

Thanks in advance

**Comment by jvinolas** [comment]
It's not possible now to modify the desktop hard disk size from IsardVDI (and not planned) as it will involve advanced guest partition and filesystem modifications. And all this will also depend on the guest type and filesystem.

Although it is possible with libguestfs to modify the qcow2 size. All this should be done manually now, modifying the qcow2 disk size and then growing the partition and filesystem inside the qcow2.

Libguestfs has some nice utilities that will help in this process. Check this out: https://libguestfs.org/virt-resize.1.html

**Comment by fgonzalezmacias** [comment]
Ok. II understand the problem. Thanks a lot. 

I close the issue.

**Comment by fgonzalezmacias** [comment]
Other usefuls links about this subject:

https://www.lafaspot.com/2017/12/how-to-resize-windows-vm-image-with.html

https://mike42.me/blog/how-to-resize-a-windows-vm-image-with-virt-resize

**Comment by bevinhex** [comment]
this is how I did it https://blog.bevin.io/2021/09/09/resize-kvm-image-qcow2/
