### ISSUE TITLE
At Domain-> Desktops I edit and delete at Media-> a Iso,  and I apply Modify Desktop, but the ISO is not delete from the Desktop

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#286]
![image](https://user-images.githubusercontent.com/72935746/97210883-83f48f80-17be-11eb-8747-707905830164.png)

Apparently, the Desktop saved the modification, but when I edit again the Dektop, the iso is associated.

If I to do the same operation at USER->Desktop the Iso file is delete correctly

Thanks

**Comment by fgonzalezmacias** [comment]
I have the develop version.

**Comment by sim6** [comment]
The medias aren't listed at desktop details of admin menu. Editing it the medias are listed in the form, but delete a media and send the form doesn't delete the media. No error shown.
