### ISSUE TITLE
When I change the Description of a Template I obtain a warning for size of the name of Desktop

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#289]
This name don't show any problem when is created. To the name of the Base Desktop is added a string whith the datetime, but when I try to change the Description of the Template, I have the warning and I can't modify neither the name, neither other field

![image](https://user-images.githubusercontent.com/72935746/97347694-6fcb9380-188d-11eb-8a8f-6d50abf8fc59.png)

**Comment by fgonzalezmacias** [comment]
The DateTime plus "-" symbol sum 15 characters, so, the length of the Desktop would be limited to 25 characters, or increase the limit of the Desktop

**Comment by sim6** [comment]
Starting a desktop via frontend creates it with the name of template prefixed by timestamp. The name field of the edit form is limited to 40 characters and edition is disabled. So if template name has more than 25 characters, then desktop edit form is unusable.

The frontend, that you can access via  e.g. https://desktops.isardvdi.com/login/default, is designed for non-persistent desktops. So, usually we don't stop non-persistent desktops and edit them. 

Users that use persistent desktops can access via admin interface, e.g https://desktops.isardvdi.com/isard-admin/login/default.

Anyway, please, could you explain your workflow?

**Comment by fgonzalezmacias** [comment]
Hi.
I'm still not sure how I am going to mount the desktops to the users - initially a very reduced environment of desktops, a pilot-


I am not sure what you call non-persistent desktops, because when the user turns off the Desktop, the desktop continues to exist as such - it is not eliminated - and if the user is logon again, it starts the desktop again, right?

On the other hand, I would like to know if you have a Windows domain environment, since in my case we all work under a Windows domain, so the issue of generating Desktops through templates, how do you manage it?

Do you create the templates, without adding to the domain, and later as you need to create desktops for the users, do you put the desktop generated through the template in the domain?

I understand that in this scenario with all users under a windows domain, all my desktops will be persistent and individuals for each user. Other thing is the installation of the software that in our case is automatically by gpo.

PD: The issue of creating a forum, do you have discarded?. I think it would be a good place to exchange knowledge between users in the community

Thank you very much for your interest in offering me support

**Comment by sim6** [comment]
A forum was not discarded. You can open a new edition to keep track of this topic.

You can put all the common settings in a template and create a desktop for each user with the user settings. Also you can create a template for each user desktop to be restored when you need it.

Ephemeral or non-persistent desktops are removed when you log out of the interface. They are also stopped or deleted after a time configured through the user category.

**Comment by fgonzalezmacias** [comment]
Ok, thanks
