### ISSUE TITLE
No 'is this a windows install?` button...

### ISSUE THREAD

**Issue by smilebasti** [isard-vdi/isard#291]
I just installed everything form scratch. It works on first try. 

I uploaded a Windows Iso and tried to install it but i can't find the Button is this a windows install media?
Otherwise i dont know where to add the extra dirver iso.

Thanks

PS: is there a tutorial to add a Domain to Isardvdi with a reverse proxy?

**Comment by smilebasti** [comment]
![image](https://user-images.githubusercontent.com/60941345/97479390-753ee180-1952-11eb-89b2-00552916873e.png)

**Comment by smilebasti** [comment]
I just read further into it but i am also not able to add iso or see the current one for a desktop.

![image](https://user-images.githubusercontent.com/60941345/97541254-1fefe800-19c5-11eb-9fdb-b2e4cd51e350.png)

I thought i schould be able to type into the iso/cd box the extra driver?

**Comment by sim6** [comment]
I'm sorry, documentation is outdated. "It is a Windows install media" checkbox is no longer available.

We are working to release the version 2. Please, could you try the `develop` branch?

To install an OS from an ISO image that doesn't have all drivers you need to add another media with the drivers before start the installation. You can use Updates menu to download a media with Virtio drivers for Windows. After create the desktop via Media menu, and before start it, edit the desktop to add the media with the drivers.

Do you mean enable external access to virtualized services with reverse proxy?

**Comment by smilebasti** [comment]
Hi, i closed this issue because it was open for 3 years.

I am not sure if i managed it to get it working. I think i switched to a different software. Currently, i don't have the need of a VDI solution to test it again. I still have isard bookmarked if that changes, i will give it another go.
