### ISSUE TITLE
web interface permit two clicks in button stop domain

### ISSUE THREAD

**Issue by alarraz** [isard-vdi/isard#3]
domain remain stopping, and is stopped. When click in domain stop button, all the screen could be blocked or disabled when the message preventing to stop appears. Broom thread must check if domain is stopped and change status from stopping to stopped.

**Comment by jvinolas** [comment]
I don't really undestand this issue. Webapp only acts when engine updates database, so UI event will be triggered when engine (broom) changes domain states. Why all the user screen should be blocked?

**Comment by jvinolas** [comment]
I close the issue due to lack of more information.
