### ISSUE TITLE
When I start a Desktop installation of a Windows 10 Desktop I don't obtain access to VirtIO drivers

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#301]
Maybe I am not understanding well the function of the template in this form, but when I install Windows 10, I select a VirtIO-type hard disk, when I try to load drivers in the Windows installation, it does not mount the ISO with the VirtIO drivers

Should I add them?

The selection of the Template has another function?

![image](https://user-images.githubusercontent.com/72935746/98381192-db5def80-2049-11eb-8037-bb962f7944ed.png)

On the other hand a couple of requests for suggestions.

I think it would be very convenient for the development of the project, if there was a forum, in which the users could help each other and it would be worth as KDB for them.

Perhaps it could be mounted on the isardvdi.com website

While this forum functionality is not implemented, if it were to be carried ou, Is there an email address where you can ask questions about the operation of IsardVDI? -which I think are not reflected in the documentation-. Not so much the bug report, which is obviously the place, but general issues.

To give an example, in the documentation I think it is not reflected, and I do not know what difference exists between the concepts of converting a Desktop into Base or Template. I don't know what the difference is between the two and what it can affect.

Thanks in advance and sorry if my last questions are not appropiate.

**Comment by sim6** [comment]
With the "Select OS template" form section you are choosing the hardware definitions.
To install an OS from an ISO image that doesn't have all drivers you need to add another media with the drivers before start the installation.
You can use Updates menu to download a media with Virtio drivers for Windows.
After create the desktop via Media menu, and before start it, edit the desktop to add the media with the drivers.

About Templates and Bases the only difference is the path where it will be stored in disk. Usually Bases will be used for many Templates, so the storage should provide a quick read access.

Feel free to open issues to get support or comment other issues to help other users.

If you prefer a private conversation you can write to info@isardvdi.com.

**Comment by fgonzalezmacias** [comment]
Ok. Thank you for the information and the clarifications.

At Domains -> Desktop when I try to add the virtio ISO for windows, before to start the Desktop,  the ISO is update, but when you edit again, the iso is not added, and the Desktop in action field, show the circle spinning continuosly.

![image](https://user-images.githubusercontent.com/72935746/98421380-804bed00-2089-11eb-9c6d-8bcfc38ef4e2.png)


![image](https://user-images.githubusercontent.com/72935746/98421307-51ce1200-2089-11eb-9677-8125e2e3f699.png)


![image](https://user-images.githubusercontent.com/72935746/98421272-40850580-2089-11eb-82ba-29b8740c2c92.png)

**Comment by fgonzalezmacias** [comment]
If the ISO is added directly from Desktop (User) the second ISO is recorded, but the Desktop show at the Action field the circle spinning.


![image](https://user-images.githubusercontent.com/72935746/98422031-fe5cc380-208a-11eb-9a4b-361006f622a1.png)

**Comment by fgonzalezmacias** [comment]
If I do docker-compose restart isard-engine I solve the problem with the start of the Desktop

I find other problem. To install W10 I detect the ISO of the Virtio Drivers, but when I load the driver, Windows say that this driver is not possible to assign to disk - I select disk Virtio at the initial configuration-

**Comment by sim6** [comment]
About edit desktop medias via admin menu (Domains -> Desktops), please update your installation to include #293.
Remember store sshd keys following the instructions of #290.

**Comment by fgonzalezmacias** [comment]
I have several problems and finally I did a new installation

I did wget https://isardvdi.com/docker-compose.yml and after I applied the instructions to migrate to develop

docker-compose up -d
docker cp isard-hypervisor:/etc/ssh ssh
docker-compose stop
wget -qO - https://isardvdi.com/docker-compose.yml | sed -e 's/v2.0.0-rc1/develop/' -e '/^    build:/d' -e '/^      \(context\|dockerfile\):/d' -e '/^      target: production$/d' > docker-compose.yml
docker-compose pull
docker-compose up -d
docker cp ssh isard-hypervisor:/etc/
docker-compose  run isard-hypervisor chown -R qemu /etc/pki/libvirt-spice

At this situation my question is how I stay update the develop installation?
docker-compose pull would be enough?



![image](https://user-images.githubusercontent.com/72935746/98449258-569ad080-2132-11eb-8315-fe5b2a939fe4.png)

I try to install Windows 10 with Virtio hard Disk driver. I suppose is the most efficient configuration, but I can't install windows on said disk

![image](https://user-images.githubusercontent.com/72935746/98449701-fd34a080-2135-11eb-8ade-17d888f62b24.png)



![image](https://user-images.githubusercontent.com/72935746/98449661-8d261a80-2135-11eb-8f39-732ae0dd90d3.png)


I don't know If my procedure is correct. I understand that if I choose SATA or IDE as Disk haven't problems in the installation of W10.

Thanks in advance

**Comment by sim6** [comment]
To update generally you can run the following instructions.
```
docker-compose pull
docker-compose stop
docker-compose rm
docker-compose up
```
About Windows installation, I can see the disk in your image, what is the problem?

**Comment by fgonzalezmacias** [comment]
Ok,  Thanks about keeping update my develop version.

Regarding the problem with the VirtIO Drivers on the hard disk, it is that in the Windows 10 installation process, the volume to be formatted appears, but when you click Next to proceed, it shows you the message of the part lower.

"No se puede crear una partición nueva ni encontrar una que ya exista........."

It was in case my procedure to try to install a Windows 10 with VirtIO hard disk driver - I understand that it is the most optimized , the VirtIO driver I mean- was not the correct one, and you would do it in another way


If I select SATA or IDE disk in the Desktop configuration, there is no problem, but I understand that the most optimal, for performance is to select VirtIO.

By the way, when I select the Default option, am I selecting VirtIO?

**Comment by rsdevigo** [comment]
Same issue with me, I can install the driver, and show the disk and partition on screen but I can´t install windows on this partition.

**Comment by fgonzalezmacias** [comment]
I have read that at other KVM systems: Proxmox, etc,  a solution is install a second hard disk, and then install Virtio Disk Driver and then change the Disk Driver of the first disk and delete the second disk.

At IsardVDI don't exist the option to install a second hard disk. Any idea? 

Has anyone successfully installed Virtio disk driver on Windows 10?

Thanks in advance

**Comment by sim6** [comment]
Please, could you try to follow the following guide:
https://isard.gitlab.io/isardvdi-docs/manager/win10_install_guide.es/

**Comment by fgonzalezmacias** [comment]
Hello. Finally with the help of the article that you gave me, I can install Windows 10 with Virtio Disk drive. Great work from IsardVDI Team!!! The documentation is of very high quality!!! Thank you

I close the issue.

**Comment by sim6** [comment]
:)

**Comment by acarfer940** [comment]
> I have several problems and finally I did a new installation
> 
> I did wget https://isardvdi.com/docker-compose.yml and after I applied the instructions to migrate to develop
> 
> docker-compose up -d docker cp isard-hypervisor:/etc/ssh ssh docker-compose stop wget -qO - https://isardvdi.com/docker-compose.yml | sed -e 's/v2.0.0-rc1/develop/' -e '/^ build:/d' -e '/^ (context|dockerfile):/d' -e '/^ target: production$/d' > docker-compose.yml docker-compose pull docker-compose up -d docker cp ssh isard-hypervisor:/etc/ docker-compose run isard-hypervisor chown -R qemu /etc/pki/libvirt-spice
> 
> At this situation my question is how I stay update the develop installation? docker-compose pull would be enough?
> 
> ![image](https://user-images.githubusercontent.com/72935746/98449258-569ad080-2132-11eb-8315-fe5b2a939fe4.png)
> 
> I try to install Windows 10 with Virtio hard Disk driver. I suppose is the most efficient configuration, but I can't install windows on said disk
> 
> ![image](https://user-images.githubusercontent.com/72935746/98449701-fd34a080-2135-11eb-8ade-17d888f62b24.png)
> 
> ![image](https://user-images.githubusercontent.com/72935746/98449661-8d261a80-2135-11eb-8f39-732ae0dd90d3.png)
> 
> I don't know If my procedure is correct. I understand that if I choose SATA or IDE as Disk haven't problems in the installation of W10.
> 
> Thanks in advance

Hi, 

I have exactly the same problem you described when I'm trying to install 32bits version from Windows 10. That's relevant because 32bits version has lower requirements than 64bits (1GB vs 2GB), and it would be used in mass mode (13/14 VMs running un parallel).

I'm using the most recent version from VirtIO Drivers for Windows (0.1.248-1) and the no UEFI version of the template (with the UEFI version it doesn't boot from CD). 

With Windows 10 64bits version and UEFI template, everything is running fine and I'm able to install Windows 11

**Comment by sim6** [comment]
For the record I edited https://github.com/isard-vdi/isard/issues/301#issuecomment-767176282 because documentations was moved (and improved).

@acarfer940 Please, to get support, could you open a new issue, preferable via https://gitlab.com/isard/isardvdi/-/issues/new ?

**Comment by acarfer940** [comment]
Finally, I solved the situation switching the Disk Bus configuration to SATA and it works like a charm!

![imagen](https://github.com/isard-vdi/isard/assets/164500953/53852503-90c8-40c4-84be-fe09e539bfaa)

**Comment by sim6** [comment]
Thanks for report it.
