### ISSUE TITLE
Dudas sobre la eliminación de Templates y Bases

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#303]
![image](https://user-images.githubusercontent.com/72935746/98452342-c28b3200-214e-11eb-9c0e-d21c802d0485.png)

No entiendo muy bien, como funciona el sistema de generación de plantillas y/o Bases en IsardVDI desde un Desktop original.

No entiendo porque si quiero borrar un Template o una Base, no pueda hacerlo sin borrar el Desktop original.

Tampoco sé como es el sistema de almacenamiento de los desktops, es decir, por ejemplo no sé si los discos son thin y si creo 5 Desktop a partir de un Template con Windows 10 de 50 GB, tendré directamente 250GB ocupados o el tamaño será inferior. 

Hola.

**Comment by sim6** [comment]
Al convertir un escritorio en plantilla el escritorio queda asociado a esa plantilla. A partir de este momento los cambios en el nuevo escritorio se efectuaran unicamente en el escritorio y no en la plantilla. A partir de la plantilla se pueden crear nuevos escritorios y estos iniciaran en el estado en que se creo la plantilla.

Los discos de las plantillas tienen la información base y los escritorios generan discos con las diferencias entre la plantilla y el escritorio. Por este motivo no se puede borrar una plantilla sin borrar los escritorios asociados ya que estos se quedarían sin los datos base. También es el motivo por el que el uso del espacio de disco no se multiplica.

**Comment by fgonzalezmacias** [comment]
Ok, ahora entiendo algo mejor el tema. Desde mi idea, yo partía de lo contrario. Creía que al Desktop, cuando se le hacía un "Template it", se creaba una copia en Template/Base y eran elemetos ya independientes, y los Desktops ya eran derivadas con los cambios del Template/Base y por tanto ya borrar un Desktop, no implicaba tener que borrar los Template/Base. Con esto habría Desktops indendientes -los originales- y Desktops derivados. Veo que el modus operandi ha sido distinto.

![image](https://user-images.githubusercontent.com/72935746/98838582-c071ed80-2444-11eb-8aab-377efa7e7615.png)

Respecto a este formulario, asociado a la categoría, en AutoDesktop Creation, selecciono los Template/Bases que quiero asociar a los usuarios con Categoría "X". Entiendo que las plantillas/Bases pueden ser una o varias, y en dicho caso saldrá la página web de select_template. ¿Estos Deskstops se borran cuando el usuario cierre sesión? o sólo ¿cuando la Categoría tenga marcado el Ephimeral Desktop, con un tiempo determinado, y seleccionado Delete? 

Si selecciono Stop, entonces ¿los Desktops se detienen pasado el tiempo estipulado, pero no se autoborran y continuan asociados al usuario, la próxima vez que el usuario se loguee? 

Gracias

**Comment by jvinolas** [comment]
The disk scheme is like this:
![imatge](https://user-images.githubusercontent.com/2132863/99634355-a639a000-2a40-11eb-8baf-d0ba1ddc4842.png)

**Comment by fgonzalezmacias** [comment]
Ok, , pero entiendo que en este esquema, faltaría la dependencia con el Desktop original, a partir del cual, al realizar el "Template it", generó el elemento BASE, ¿no?, ya que en el momento que realizo el Template It, bien como elemento Base o bien como Template, ya quedan ligados y la eliminación del Base/Template implica la eliminación del Escritorio original.

Gracias

**Comment by jvinolas** [comment]
Todos los desktops dependen en cuanto a disco de su template. Más o menos
cómo en este esquema:
[image: imatge.png]


Missatge de fgonzalezmacias <notifications@github.com> del dia dj., 19 de
nov. 2020 a les 9:58:

**Comment by jvinolas** [comment]
Cuando se genera template a partir de un desktop en realidad lo que hace Isard es mover el disco del desktop a una template (y hacer los cambios en la bbdd). Seguidamente crea un nuevo escritorio para ese usuario basado en la plantilla.

Esto puede hacer que el usuario no entienda porqué el escritorio ahora está ligado a la plantilla.

**Comment by fgonzalezmacias** [comment]
Yo veo más natural, el que el Escritorio original y la plantilla derivada, no tuvieran relación directa, una vez realizado el Template It

Es decir, una vez yo estoy creando un Escritorio base inicial, con la configuración deseada, para un departamento o conjunto de usuarios, al convertirlo en Base/Plantilla, copiaría el disco y crearía el disco Base/Template, pero independiente, así yo podría seguir realizando derivadas de mis Escritorios originales de trabajo, y no afectarían a otros discos ya considerados plantillas. No sé lo veo más natural, supongo que cuando lo habéis hecho de esta forma, lo habréis valorado, pero a mí me parece más intuitivo, pensar que un escritorio, una vez lo convierto en plantilla, ya son dos objetos independientes. Con esto podría eliminar cuando quisiera mis Escritorios iniciales, y la dependencia se iniciaría a nivel de Base/Template

Gracias

**Comment by sim6** [comment]
El escritorio que se usa para crear la plantilla se queda como derivado de la plantilla. Por lo tanto queda ligado a la plantilla como cualquier otro escritorio derivado de esa plantilla.
Por lo tanto puedes eliminar el escritorio que has usado para crear la plantilla sin borrar la plantilla.
También puedes generar otra plantilla del escritorio inicial en este caso quedaría el siguiente esquema.
* Primera plantilla creada
  * Escritorio derivado de la primera plantilla
  * Segunda plantilla creada
    * Escritorio inicial
    * Escritorio derivado de la segunda plantilla

De esta forma puedes primero crear un escritorio genérico he ir añadiendo configuraciones más especificas ir creando más plantillas del escritorio inicial o de los derivados. Llegando a un esquema como este:
```
1. Plantilla: Primera plantilla creada desde el escritorio inicial
  1.1. Plantilla: Segunda plantilla creada desde el escritorio inicial
    1.1.1. Plantilla: Tercera plantilla creada desde el escritorio inicial
      1.1.1.1. Escritorio inicial
      1.1.1.2. Escritorio: Escritorio derivado de la plantilla 1.1.1
    1.1.2. Escritorio: Escritorio derivado de la plantilla 1.1
  1.2. Escritorio derivado de la plantilla 1
  1.3. Plantilla: Plantilla creada desde el escritorio 1.3.1 que fue creado mediante la plantilla 1
    1.3.1. Escritorio derivado de la plantilla 1 y usado para crear la plantilla 1.3
    1.3.2. Escritorio derivado de la plantilla 1.3
```

**Comment by fgonzalezmacias** [comment]
Ok, gracias Simó, creo que ahora lo entiendo.

Saludos
