### ISSUE TITLE
Incorrect login credentials aunque estoy seguro de estar metiendo correctamente la contraseña establecida

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#304]
Hola.

A la hora de logonearme como un usuario, el cual tiene asignada una categoría, obtengo un "Incorrect login credentials", cuando estoy seguro que estoy metiendo correctamente el password establecido, por lo tanto me hace pensar en dos cosas:

1) Bien el password no es correctamente registrado a la hora de crear el usuario o

2) Existe algún otro problema de autorizaciones a la hora de crear y asignar categorías o grupos y no me está motrando dicho error, sino el de password

![image](https://user-images.githubusercontent.com/72935746/98452895-d08f8180-2153-11eb-99ee-81990b1cb0e6.png)

No sé si puede ser la causa, pero un posible pufo es que a la hora de asignar unos permisos por categoría a un Desktop, si edito los permisos, visualizo el permiso asignado, pero en el registro, a nivel de fila en el formulario previo, no lo actualiza

![image](https://user-images.githubusercontent.com/72935746/98452968-86f36680-2154-11eb-8965-0d39bd781803.png)

Aquí se ve que si lo edito ya estaba previamente -no he añadido nada-, sin embargo se ve como el contenido a nivel de registro, no muestra la asignación de la Categoría Redacción al Desktop

**Comment by sim6** [comment]
Cada categoría tiene que acceder mediante una URL distinta. Por ejemplo la categoría test tiene el acceso de escritorios efímeros en:
https://desktops.isardvdi.com/login/test
Y la gestión de escritorios:
https://desktops.isardvdi.com/isard-admin/login/test

Referente al formulario de permisos estos se reflejan en los detalles de la plantilla, pulsando el botón +. Pero efectivamente no se refresca automáticamente. Esto mejor lo tratamos en otro "issue".

**Comment by fgonzalezmacias** [comment]
Ok, Simó, ahora perfectamente entendido. Esto creo que no viene en la documentación del proyecto -o por lo menos, no lo he encontrado-, y te aseguro que puede despistar bastante.


PD: Cuando me he logoneado en https:/miip.com/login/financiero , me salía para seleccionar tanto la platilla de BASE como el template. En el Template sí tenía marcado la categoría financiero, pero en la plantilla de BASE, sólo tenía marcado categoría, pero sin añadir ninguna en concreto. Cuando he desmarcado la categoría asociada a la plantilla de base, ya no me ha salido el formulario de select_template y he entrado directamente en el template, que es el que tenía asociada la categoría de Financiero. No sé si se considera un pufo, o en el momento de tener marcado Categoría en un Template/BASE aunque no se concrete cual, ya valida para cualquier.

No sé si me he explicado correctamente.

Esta incidencia dala por cerrada y ya según lo que veas del comentario último abres otra o no.

Muchísimas gracias Simó

**Comment by sim6** [comment]
Efectivamente, al marcar la casilla de compartir sin especificar elementos se comparte con todos.

Esta documentado para la interfaz completa pero no para la simple.
https://isardvdi.readthedocs.io/en/develop/interfaces/web/

Permitame dejar esta incidéncia abierta hasta que se añada.

**Comment by fgonzalezmacias** [comment]
Por supuesto. Muchas gracias

**Comment by sim6** [comment]
Closed due to issue number conflict with gitlab.

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
