### ISSUE TITLE
When I create a Category show an error message although the Category and associated group is created

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#309]
![image](https://user-images.githubusercontent.com/72935746/98589668-e9bc3d80-22cd-11eb-828a-72426614645d.png)

It occurs when either of the two checks is marked to select or both

**Comment by sim6** [comment]
I cannot reproduce it. Please, could you explain it step by step.

**Comment by fgonzalezmacias** [comment]
Now I can't reproduce the incident either. I close it

Thanks
