### ISSUE TITLE
The desktop edit form is unusable if the desktop name is longer than 40 characters.

### ISSUE THREAD

**Issue by sim6** [isard-vdi/isard#311]
The desktop edit form has a 40 character limit for the name, but name editing is disabled.
If we have a desktop with a name longer than 40 characters the edit form is unusable.

See also #302

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
