### ISSUE TITLE
Internalization of the end-user web interface

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#313]
Hello.

Currently for the end user, the access forms are in Catalan. I think it would be interesting to be able to customize the language in these forms, to adapt them to that of our users, although obviously for Spanish speakers they are perfectly understood.

**Comment by sim6** [comment]
Thanks for reporting, @NefixEstrada are working on this.

**Comment by fgonzalezmacias** [comment]
Ok. Thanks a lot

**Comment by NefixEstrada** [comment]
It's getting merged here! https://gitlab.com/isard/isardvdi/-/merge_requests/4

We're also thinking about using Weblate or something like that in order to make it easier for contributors to translate the interface to other languages!

**Comment by fgonzalezmacias** [comment]
I think would be an interesting option.

Thanks...

**Comment by NefixEstrada** [comment]
I'll try to set it up then! :)
