### ISSUE TITLE
Setup Weblate for localization

### ISSUE THREAD

**Issue by NefixEstrada** [isard-vdi/isard#315]
Weblate is a web interface for localization. It would be useful,  because it would enable IsardVDI to be translated to other languages that we don't know and improve the current translations.

This is a #313 followup

**Comment by NefixEstrada** [comment]
Now it's created! :D

We should try to update CONTRIBUTING.md to reflect those changes!

**Comment by sim6** [comment]
I configured unmet guidelines to have the project approved by weblate.org.
- Configure repository hooks for automated flow of updates to Weblate. 
- Define translation instructions to give translators a guideline. 
- Add screenshots to show where strings are being used.
- Use flags to indicate special strings in your translation.

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
