### ISSUE TITLE
To create a forum to exchange knowlegement between users of IsardVDI

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#316]
Hello

To relate https://github.com/isard-vdi/isard/issues/289 I think would be interesting to have an forum to exchange information between the users of IsardVDI.

Perphaps this forum could be associated to the web of the project www.isardvdi.com

It's only a idea

**Comment by sim6** [comment]
Please could you elaborate the benefits of a forum. Meanwhile feel free to open issues to get support.

**Comment by fgonzalezmacias** [comment]
Basically it is the one you comment on, and thus differentiate the incidents open in github with respect to possible bugs of the application, rather than doubts or ignorance about the use of it.

It is a tool that usually exists in many open-source and other projects and that I believe helps to consolidate the knowledge of users, and to help those who are new to it


If a question about the operation or a very specific problem is opened on github, it seems that the question is being asked exclusively to users who support the project, and perhaps other users are not encouraged to contribute, even knowing the problem, with the Using the forum, I think that the intervention of all users is opened.

I myself after three weeks using the application I still have conceptual doubts about it, and how to adapt its operation in the most optimal way to my productive environment, and I understand that your time should be more directed to improving the project, than to solve my earthly doubts. ;-))


It's just an idea, and I may be wrong in my reasoning, obviously.

Thank you so much for everything

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
