### ISSUE TITLE
To reset password of users, althought you enter a not coincident password show message that the user is updated

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#317]
Show the message that the passwor is not coincident, but after show message that the user is updated.

Thanks

**Comment by sim6** [comment]
I can't reproduce it using the "develop" version. Is this issue a duplicate of #145 that is present in version v2.0.0-rc1?

**Comment by fgonzalezmacias** [comment]
I'm trying now, and Icant reproduce the issue.

I close the issue. 

Thanks
