### ISSUE TITLE
After installing Isard via Quick Start with docker & docker-compose i'll get a 503 Service Unavailable Error.

### ISSUE THREAD

**Issue by nicrieser** [isard-vdi/isard#320]
When i run docker-compose up -d, all the containers start, isard-stats and isard-db wont start. The webinterface site is reachable but gives me an 503 Service Unavailable Error.
Docker is on newest Version and everything is default.

**Comment by nicrieser** [comment]
Starting isard-db ... error
ERROR: for isard-db  Cannot start service isard-db: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/var/lib/docker/overlay2/03354be39219c477d2d66b8e976a7125c6c87d4fdc302cc25728fdf3685a83fe/merged\\\" at \\\"/var/lib/docker/overlay2/03354be39219c477d2d66b8e976a7125c6c87d4fdc302cc25728fdf3685a83fe/merged/usr/share/zoneinfo/UCT\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for isard-db  Cannot start service isard-db: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/var/lib/docker/overlay2/03354be39219c477d2d66b8e976a7125c6c87d4fdc302cc25728fdf3685a83fe/merged\\\" at \\\"/var/lib/docker/overlay2/03354be39219c477d2d66b8e976a7125c6c87d4fdc302cc25728fdf3685a83fe/merged/usr/share/zoneinfo/UCT\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by jvinolas** [comment]
It seems that is trying to map host /etc/localtime and your host OS does not have it. Which host OS are you using?

**Comment by nicrieser** [comment]
> It seems that is trying to map host /etc/localtime and your host OS does not have it. Which host OS are you using?

I'm using windows 10 pro. I guess paths do not directly translate to windows paths? But i got it working on a linux vm
