### ISSUE TITLE
Isard media downloads won't start and cannot get abborted

### ISSUE THREAD

**Issue by nicrieser** [isard-vdi/isard#321]
I'm sorry for opening the third Issue today haha,

Isard won't start any media downloads, not the premade ones, and none of them i'll add. It just says DownloadStarting, and nothing happens. Then I'm not able to abort/delete them.

Is it because I'm running Isard in a VM?

**Comment by sim6** [comment]
Do you enabled nested virtualization?

**Comment by nicrieser** [comment]
got it working, thank you
