### ISSUE TITLE
Network configuration at VDI clients

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#322]
Hello

My VDI clients will be normally Windows client, integrated in a domain. If i deploy a VDI client I obtain a IPV4 configuration as follow:

192.168.121.82
255.255.252.0
192.168.120.1

With this configuration obtained automatically by IsardVDI configuration, I can ping any resource on my network, which is type 10.X.Y.Z with mask 255.255.0.0, but from my corporate network, I cannot directly access these desktops, that is, I am not able to ping to it .

Could it be done so that the desktops took DHCP directly from my infrastructure's DHCP server?

Thanks in advance

**Comment by jvinolas** [comment]
libvirt creates a NAT router to the vms using iptables (or firewalld if you configured with this). 
So you should open rules in your iptables/firewalld host to allow access to those guest ips.

**Comment by fgonzalezmacias** [comment]
Ok, thanks. I will investigate about it.

Some information in the documentation in this regard would be very interesting

**Comment by jvinolas** [comment]
We are working in giving access to guest IP with wireguard through the web interface.

**Comment by fgonzalezmacias** [comment]
Great!!!!
That would be a great step for the project.

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
