### ISSUE TITLE
Problems with USB redirections

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#323]
Hello

I have problems to obtain a USB redirection from my computer to VDI Desktop.

Any idea about this problem?

The USB pendrive is good, is formated, and I can view its content.

Thanks in advance

![Redirecting USB1](https://user-images.githubusercontent.com/72935746/99915790-0ca31480-2d06-11eb-950f-2bcee8255e3d.png)

![Redirecting USB2](https://user-images.githubusercontent.com/72935746/99915792-1298f580-2d06-11eb-8530-6d7ee654fc0e.png)

**Comment by jvinolas** [comment]
With a windows client you should install: https://www.spice-space.org/download/windows/usbdk/UsbDk_1.0.22_x64.msi

**Comment by fgonzalezmacias** [comment]
This UsbDK_1.0.22_x64.msi is to intall in source desktop or vdi desktop?

Thanks

**Comment by fgonzalezmacias** [comment]
I install the msi at vdi desktop and I obtain the next error:

![image](https://user-images.githubusercontent.com/72935746/99947456-4d3b7600-2d78-11eb-9d3f-5a084a6fe359.png)

**Comment by fgonzalezmacias** [comment]
Finally I can view the USB pendrive at my desktop, when I install the UsbDK_1.0.22_x64.msi at my source computer.

 I am not sure if the msi must be installed on the source computer of the connection or on both?

**Comment by fgonzalezmacias** [comment]
Finally I discover that the msi must be installed at source computer.

Thanks
