### ISSUE TITLE
Doubt about opening the desktop from the source computer

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#324]
Actually when I open a desktop with virt-viewer, a file is downloaded with .vv extension, and when I do to open the virt-wiever is opening, and I obtain my desktop

I understand that this is the process and that there is no way that when clicking on the option to use the virt-viewer, the desktop is opened, without downloading the .vv file

![image](https://user-images.githubusercontent.com/72935746/99948994-9c82a600-2d7a-11eb-88e4-a8fac24249d6.png)

Thanks in advance

**Comment by fgonzalezmacias** [comment]
After update the project I read the login page information and the text is clear.

![image](https://user-images.githubusercontent.com/72935746/100347537-d3a8bf80-2fe5-11eb-8b79-d4516bb65fd6.png)


Thank you

**Comment by sim6** [comment]
If you update it again you will see instructions to install local client in this page.

**Comment by fgonzalezmacias** [comment]
Yes, thank you. I update my system. I saw the link to download the x64 and x32 clients, but this is not my question. I observed that any times when I press the "Cliente local" option, a file with extention .vv is downloaded and I have to open it to open the spice client, and othe times when I press the "Cliente local" option the spice client is directly open, 
without a file being visibly downloaded.

What is this behavior due to?

**Comment by fgonzalezmacias** [comment]
I think it is a good decision to have a single form -single url- for all categories and that the user selects based on their membership

**Comment by sim6** [comment]
Please, could you open new issues to speak about not related topics?

About the login form, if you update your installation you will see a category selector.

About the vv file, what browser and OS are you using?

**Comment by fgonzalezmacias** [comment]
Ok. I'm sorry

Yes, I see the category selector. I think is a good decision.

My source OS is Windows 10, my browser is Chrome and my target OS is Windows 10 -IsardVDI-.

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
