### ISSUE TITLE
Intentando comprender conceptos sobre escritorios permanentes y efímeros en IsardVDI

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#325]
Hola.

En los días que llevo conociendo a IsardVDI, estoy montando Escritorios, convirtiéndolos a Tamplates -ya me comentéstais que el concepto de BASE, posiblemente se elimine en próximas versiones- y creando usuarios, a los cuales le asigno una categoría -en mi escenario equivale a  departamento-, y a los templates les asocio una categoría, y por ende un departamento. Es decir creo un template, para cada departamento de mi organización.

Con esto consigo que Usuario1, que está asociado a la categoría Publicidad, se le genere un escritorio de forma automática del tipo que he preparado para el Departamento de Publicidad, y hasta aquí ok.

Yo en la creación de categorías, no usaba ninguno de los dos checks existentes, ni el de Auto Desktop Creation, ni el de Ephimeral Desktops. El primero o no hace bien su función o no lo entiendo, abriré otro caso comentándolo, y el segundo, porque no serían de uso ahora mismo en mi escenario.

![image](https://user-images.githubusercontent.com/72935746/99957812-94c9fe00-2d88-11eb-856e-0562c4d94196.png)

El caso es que mis escritorios en un 95% deberán ser permanentes, en mi escenario profesional, no tiene sentido que los escritorios se vayan eliminando y regenerándose otros nuevos de las mismas características

En un issue anterior ya me comentásteis que:

"Cada categoría tiene que acceder mediante una URL distinta. Por ejemplo la categoría test tiene el acceso de escritorios efímeros en:
https://desktops.isardvdi.com/login/test
Y la gestión de escritorios:
https://desktops.isardvdi.com/isard-admin/login/test"

Yo hasta hoy veía que los escritorios que se creaban automáticamente por un usuario al logonearse, cuando éste tenía asociado una categoría y la categoría estaba asociada a un Template, se mantenían, pero hoy me dió  por dar a la opción de abajo, de "Sortir", y he visto como el Desktop se eliminaba.

¿Existe alguna forma de que el darle a Sortir, no elimine el Desktop?
![image](https://user-images.githubusercontent.com/72935746/99959065-af04db80-2d8a-11eb-89c4-1dbd09e68f5c.png)

Si mis usuarios van a trabajar con Escritorios permanentes, entiendo que tendrán que logonearse por:

https://miip.com/isard-admin/login/redaccion por ejemplo, pero al logonearme aquí, e intentar añadir un nuevo Desktop, veo que no me deja asociar un Template, no me sale ninguno.¿Esto es porque la cuenta de usuario es del tipo User? Tendré que asignar una cuenta de tipo Administrador a los usuarios permanentes?

No sé si me he explicado muy bien, y habés cogido idea de mis dudas

Muchas gracias

![image](https://user-images.githubusercontent.com/72935746/99959447-52ee8700-2d8b-11eb-85cf-a353e55315c3.png)

**Comment by jvinolas** [comment]
Estamos trabajando en una versión que permita los persistentes en el frontend de usuario sin necesidad de acceder al apartado de administración.

**Comment by fgonzalezmacias** [comment]
Ok, me vendrá genial en mi escenario.

**Comment by jvinolas** [comment]
Tiene más o menos esta pinta:
https://user-images.githubusercontent.com/2132863/105374872-722d5780-5c08-11eb-9ef1-6e4d90760804.mp4

**Comment by fgonzalezmacias** [comment]
Creo que muy bien. Muchas gracias por el feedback

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
