### ISSUE TITLE
Auto Desktop Creation 

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#326]
I am not clear about the functionality of this option, since if I associate a Template, later at the Template level, I do not see the category to which I have associated

![image](https://user-images.githubusercontent.com/72935746/99959949-399a0a80-2d8c-11eb-9842-cfdb6b9a88f8.png)

I until now go to template and then I associated the category.

Thanks

**Comment by jvinolas** [comment]
This option will force all users in that category to have a desktop from those templates created when they login, even if they delete it. It was a feature a client requested but personally I can't think of an scenario where it is useful...

**Comment by fgonzalezmacias** [comment]
My reasoning is that I understand that if a template is associated with a category, in this process of AutoDesk Creation,  it should appear at the template level, that category, but not is not associated.

![image](https://user-images.githubusercontent.com/72935746/100997024-145e8680-355a-11eb-9657-62b9415c76bf.png)

I  don't know if I'm explaining myself correctly

Thanks

**Comment by fgonzalezmacias** [comment]
I update my system to the last develop version of this morning.

![image](https://user-images.githubusercontent.com/72935746/101176408-bbb8e780-3646-11eb-91e3-46c3c405e18e.png)

I think that when I create a new category and select auto desktop creation -this option i don't use- and I select a template, by example "Template W10 Base", this association must will be seen at the permissions form of the template


![image](https://user-images.githubusercontent.com/72935746/101176646-0f2b3580-3647-11eb-83ba-7f7ae2236e68.png)

or they are different things and they do not have to be related?

Perhaps I am misinterpreting the meaning of this association

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
