### ISSUE TITLE
Disable delete and modify characteristics user desktop

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#330]
If I have a scenario, where most of my desktops will be permanent, and I have to enter https://miip.com/isard-admin/login/category, the user can modify characteristics of its desktop, by example Disk Bus, that your change can make the desktop no longer operational.

I think it would be interesting to have some permission at the user level to enable or disable these options.

![image](https://user-images.githubusercontent.com/72935746/100134458-86fba200-2e88-11eb-97d0-b05ca51b39a1.png)

**Comment by fgonzalezmacias** [comment]
![image](https://user-images.githubusercontent.com/72935746/100137877-76015f80-2e8d-11eb-8482-0cd8d7a13b5f.png)

**Comment by jvinolas** [comment]
I see. There is no option for disk bus at the domains-resources to modify the permission level. At that page you can set or unset the available options for resources, but none for disk bus...

Maybe an option is to just add an option to fully block users edit of their desktops?

**Comment by fgonzalezmacias** [comment]
I don't understand

When I login at https://ipserver/isard-admin/login/user_category,  the user have available this form, and I can modify several parameters, disk bus incluided

But in any case, it seems good to me that there was an option at the user level, to prevent them from modifying their desktops


![image](https://user-images.githubusercontent.com/72935746/100995515-2d663800-3558-11eb-86fb-94ba3580fa6d.png)

Thanks in advance

**Comment by fgonzalezmacias** [comment]
I understand that the user is logoned at https://myip/ and the only diference is that the user have the posibility of delete the Desktop when Exist option is pressed. To my users I prefer this option to enter my users that the other way http://myip/isard-admin/login/category, but I don't want that the users can delete the Desktop

Would be possible to associate a general configuration option to disable the delete of the Desktop with the exit option?

I don't want that my users have any possibility to change any option of the Desktop, exist any diference between to login from https://myip/ or https://myip/isard-admin/login/category?, -with the assumption that the user could not modify any feature of his desktop-

Thanks in advance

**Comment by jvinolas** [comment]
Hi,

What you want is that the user frontend (https://myip) that now is used only for non persistent desktops has also an option for persistence, so the user has always the same desktops available, not a new one each time.

We are working in this feature (persistent desktops in user frontend) that won't be deleted after the user logout. I think it will meet your needs.

Hope we have it soon!
