### ISSUE TITLE
Load Error (Internal Server Error) when I try to delete a Base or Template

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#337]
This is the error. I try to stop containers and reboot the server.

Any possible solution?

![image](https://user-images.githubusercontent.com/72935746/100988195-be84e100-354f-11eb-99bb-d601b356a26c.png)

**Comment by jvinolas** [comment]
Could you provide logs concerning that error located at /opt/isard-local/logs/webapp/webapp-error.log?

**Comment by fgonzalezmacias** [comment]
I attach the webapp-error.log


In any case, the error no longer appears. I don't know if it's a coincidence, but after deleting a desktop, it already seems to be correct, when I want to delete a Base or Template



[webapp-error.txt](https://github.com/isard-vdi/isard/files/5635241/webapp-error.txt)

**Comment by fgonzalezmacias** [comment]
The error appears again. I have been able to remove the Base template and some other TEmplate, but removing the following one already showed the error again

![image](https://user-images.githubusercontent.com/72935746/100994884-5fc36580-3557-11eb-9543-d4986a8a723f.png)

**Comment by jvinolas** [comment]
For what I see in the logs seems familiar to me. I remember fixing that bug in recent PR. Do you have the latests develop images?

**Comment by fgonzalezmacias** [comment]
Yes I have the last develop images about seven or eight days ago. 

In any case, I redid my installation. If I find the problem again, I will report it. Thank you
