### ISSUE TITLE
Download starting when  the name of the ISO is not modified of the default

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#338]
I have the suspicion that if it is assigned as a name in the form, the one assigned by default from the ISO, the download does not start and stays at Download Starting, however if a different name is assigned, it is done

![image](https://user-images.githubusercontent.com/72935746/101016687-69ee5f80-3569-11eb-853e-a2d3bbb238eb.png)

![image](https://user-images.githubusercontent.com/72935746/101016814-8ee2d280-3569-11eb-8b19-33999c57f459.png)

**Comment by fgonzalezmacias** [comment]
![image](https://user-images.githubusercontent.com/72935746/101017096-ec771f00-3569-11eb-9459-50ef93476b96.png)

**Comment by sim6** [comment]
I can't reproduce it.

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
