### ISSUE TITLE
Version virt-viewer-x64-7.0.msi as recomended download when exist the version virt-viewer-x64-9.0.msi

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#344]
I saw this version at https://virt-manager.org/download/

I use the virt-viewer-x64-9.0.msi and until now, all it's ok

Any reason to not use this last version?

![image](https://user-images.githubusercontent.com/72935746/101799854-e7d3dd00-3b0c-11eb-818f-27e9bf968b2f.png)

Thanks in advance

**Comment by jvinolas** [comment]
No. I think the link it is updated on latest develop

**Comment by fgonzalezmacias** [comment]
I just to update my installation and I get the next link

![image](https://user-images.githubusercontent.com/72935746/102026250-018b5380-3d9d-11eb-9079-3ec3b943b988.png)

**Comment by jvinolas** [comment]
I think should be updated now.

**Comment by fgonzalezmacias** [comment]
I just updated the installation and I keep seeing the link pointing to version 7.0 of the spice client

![image](https://user-images.githubusercontent.com/72935746/107286284-abffba00-6a60-11eb-8e19-8570ecdef013.png)

**Comment by fgonzalezmacias** [comment]
I update my installation now and the link is to download the 7.0 version and not the 9.0

![image](https://user-images.githubusercontent.com/72935746/109325983-e4700800-7856-11eb-8492-9e1975930cf3.png)

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
