### ISSUE TITLE
FailedCreatingDomain

### ISSUE THREAD

**Issue by jorgezarate** [isard-vdi/isard#345]
libvirt: Network Driver error : Requested operation is not valid: network 'private2' is not active
2020-12-10 20:07:53,839 - workers - ERROR - worker_isard-hypervisor - Exception in libvirt starting paused xml for domain _local-default-admin-admin-demo in hypervisor isard-hypervisor. Exception message: "Requested operation is not valid: network 'private2' is not active" 
2020/12/10 20:07:53 839 - ERROR - worker_isard-hypervisor: Exception in libvirt starting paused xml for domain _local-default-admin-admin-demo in hypervisor isard-hypervisor. Exception message: "Requested operation is not valid: network 'private2' is not active"

**Comment by jvinolas** [comment]
It seems that the networks where not populated. Could you enter the hypervisor and check if they are active?

# docker exec -ti isard-hypervisor /bin/sh
/ # virsh net-list
 Name       State    Autostart   Persistent
---------------------------------------------
 default    active   yes         yes
 private1   active   yes         yes
 private2   active   yes         yes
 private3   active   yes         yes
 private4   active   yes         yes
 private5   active   yes         yes
 shared     active   yes         yes

**Comment by jorgezarate** [comment]
root@vDesktop:~# docker exec -ti isard-hypervisor /bin/sh
/ # virsh net-list
 Name   State   Autostart   Persistent
----------------------------------------


it's empty

**Comment by jorgezarate** [comment]
I made a clear install
