### ISSUE TITLE
Do you  know why ?

### ISSUE THREAD

**Issue by jorgezarate** [isard-vdi/isard#349]
libvirt:  error : Unable to set bridge virbr0 port vnet0 isolated to 1: Invalid argument
2020-12-15 06:42:39,297 - workers - ERROR - worker_isard-hypervisor - Exception in libvirt starting paused xml for domain _local-default-admin-admin-demo4 in hypervisor isard-hypervisor. Exception message: 'Unable to set bridge virbr0 port vnet0 isolated to 1: Invalid argument' 
2020/12/15 06:42:39 297 - ERROR - worker_isard-hypervisor: Exception in libvirt starting paused xml for domain _local-default-admin-admin-demo4 in hypervisor isard-hypervisor. Exception message: 'Unable to set bridge virbr0 port vnet0 isolated to 1: Invalid argument'

**Comment by jvinolas** [comment]
It could be any selinux or apparmor active in host that forbids network creation inside docker isard-hypervisor? Could you get inside the isard-hypervisor (docker exec -ti isard-hypervisor /bin/sh) and do a brctl show?

**Comment by jorgezarate** [comment]
It's Debian Linux vDesktop 4.9.0-14-amd64 #1 SMP Debian 4.9.240-2 (2020-10-30) x86_64 GNU/Linux

Clear install,  selinux or apparmor 

root@vDesktop:~# systemctl stop apparmor
Failed to stop apparmor.service: Unit apparmor.service not loaded.

root@vDesktop:~#  cat /etc/selinux/config
cat: /etc/selinux/config: No such file or directory

root@vDesktop:~# docker exec -ti isard-hypervisor /bin/sh
/ # brctl show
bridge name	bridge id		STP enabled	interfaces
virbr0		8000.52540047b369	yes		virbr0-nic
virbr1		8000.52540047b370	yes		virbr1-nic
virbr11		8000.5254000713f9	yes		virbr11-nic
virbr12		8000.525400b985d1	yes		virbr12-nic
virbr13		8000.525400bb62cb	yes		virbr13-nic
virbr14		8000.525400f5758c	yes		virbr14-nic
virbr15		8000.525400d82322	yes		virbr15-nic

**Comment by jvinolas** [comment]
Everything seems correct at network level. Could you check inside hypervisor virsh net-list and check which networks do you have active?

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
