### ISSUE TITLE
Network resource update overwrites alloweds

### ISSUE THREAD

**Issue by jvinolas** [isard-vdi/isard#357]
When editing network resource there are two bugs:
- The button name says 'add new network' instead of 'update network'
- The alloweds are overwitten with none access.

**Comment by sim6** [comment]
Second point done via https://gitlab.com/isard/isardvdi/-/merge_requests/466

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
