### ISSUE TITLE
Spice client is closed when I try to connect by url

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#363]
When I try to connect to a desktop of a user, by the url, the spice client of the user is closed.

Is it correct? Any solution?

The desktops are in a different subnet than my infrastructure, so I use the link to support and connect to the user desktop and view with him, the problem or incident.

![image](https://user-images.githubusercontent.com/72935746/105060734-05d01e00-5a79-11eb-9496-537a9ee94b2f.png)

![image](https://user-images.githubusercontent.com/72935746/105060481-c0135580-5a78-11eb-87a9-32488b08c3b7.png)

Thanks in advance

**Comment by jvinolas** [comment]
You can't have more than one viewer connected with spice. The last to connect gets the viewer from the other one. But you can have HTML5 and spice at the same time from two clients.

**Comment by fgonzalezmacias** [comment]
Ok, thank you.
