### ISSUE TITLE
Imposible to validate with admin user

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#366]
After updating my installation, I can no longer log in as an administrator.

I did

wget https://isardvdi.com/docker-compose.yml
docker-compose pull
docker-compose stop
docker-compose rm -f
docker-compose up -d

I use the default username and password and I can't validate myself: admin / IsardVDI

However user validation does work

I have restarted the containers, and even the server and nothing, I can't validate myself.

Previously there was no problem in the validation with the admin user

Any ideas?

**Comment by jvinolas** [comment]
If you didn't remove the database (/opt/isard/database) the password should be the same as before.

**Comment by fgonzalezmacias** [comment]
Solved. It was a customer problem. After restarting the client computer it already worked

Thank you
