### ISSUE TITLE
Check to user level to on/off the posibility of have temporal desktops

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#374]
I like the organization of users through categories, but in the persistent VDI creation scenario, it would seem appropriate to have a check at the user configuration level, to enable or not the creation of temporary desktops

![image](https://user-images.githubusercontent.com/72935746/107027883-0b35a400-67ad-11eb-8c57-8624f3905945.png)

Thanks in advance

**Comment by sim6** [comment]
Thanks for the idea, we discussed it as a general option, not yet implemented. Meanwhile, users who do not have access to any templates will not be able to create temporary desktops.

**Comment by fgonzalezmacias** [comment]
Ok, thank you. I close the issue.
