### ISSUE TITLE
Problem to login with admin user

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#381]
After I update the installation, when I go to the admin enter link:

https://ipserver/isard-admin/login

![image](https://user-images.githubusercontent.com/72935746/107997858-217d0480-6fe4-11eb-935a-0257d0fd69cc.png)

Thanks in advance

**Comment by sim6** [comment]
Please, try https://ipserver/isard-admin/login/

**Comment by fgonzalezmacias** [comment]
Thank you. The problem was the last slash

**Comment by fgonzalezmacias** [comment]
I stay open to review of the kind/bug
