### ISSUE TITLE
Found orphan containers -isard-stats-

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#384]
I obtain this message when I update the installation about 5 minutes ago

![image](https://user-images.githubusercontent.com/72935746/108721113-ec137200-7521-11eb-8064-d850a0b3b04f.png)

Thanks

**Comment by sim6** [comment]
You can remove it. We disabled it due it isn't working properly and we are desinging a solution.

**Comment by fgonzalezmacias** [comment]
Ok, thanks. I close the issue.
