### ISSUE TITLE
Error on  docker-compose pull

### ISSUE THREAD

**Issue by transparent-DR** [isard-vdi/isard#390]
root@gpv-support-vdi-01:/isardvi# wget https://isardvdi.com/docker-compose.yml
--2021-03-23 01:37:14--  https://isardvdi.com/docker-compose.yml
Resolving isardvdi.com (isardvdi.com)... 5.9.107.10
Connecting to isardvdi.com (isardvdi.com)|5.9.107.10|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://gitlab.com/isard/isardvdi/-/jobs/artifacts/develop/raw/docker-compose.yml?job=docker-build [following]
--2021-03-23 01:37:14--  https://gitlab.com/isard/isardvdi/-/jobs/artifacts/develop/raw/docker-compose.yml?job=docker-build
Resolving gitlab.com (gitlab.com)... 172.65.251.78, 2606:4700:90:0:f22e:fbec:5bed:a9b9
Connecting to gitlab.com (gitlab.com)|172.65.251.78|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://gitlab.com/isard/isardvdi/-/jobs/1108769749/artifacts/raw/docker-compose.yml [following]
--2021-03-23 01:37:15--  https://gitlab.com/isard/isardvdi/-/jobs/1108769749/artifacts/raw/docker-compose.yml
Reusing existing connection to gitlab.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 22475 (22K) [application/octet-stream]
Saving to: ‘docker-compose.yml.1’

docker-compose.yml.1                              100%[============================================================================================================>]  21.95K  --.-KB/s    in 0.001s

2021-03-23 01:37:15 (30.8 MB/s) - ‘docker-compose.yml.1’ saved [22475/22475]

root@gpv-support-vdi-01:/isardvi# docker-compose pull
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.isard-engine.depends_on contains an invalid type, it should be an array

Sorry, but I am new to Docker/YAML

**Comment by transparent-DR** [comment]
This link seems to work, the one on the main web page is different.

wget https://raw.githubusercontent.com/isard-vdi/isard/master/docker-compose.yml

**Comment by sim6** [comment]
Please, don't use master branch. Please, use docker-compose version >= 1.27.3.
You can get the last version via the following command:
```
pip install docker-compose
```

**Comment by transparent-DR** [comment]
Thank you for the response.  

Item to consider, that the instructions on the front web page: "Quick Start" will not work, if followed.

**Comment by sim6** [comment]
Yes, I'm sorry. This is a recent incompatibility between old docker-compose versions and the docker-compose version of CI that generates the docker-compose file.

**Comment by transparent-DR** [comment]
No problem, I like the product and wish to see a large community

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by transparent-DR** [comment]
Still having issues.  I am trying to get this to work under docker / opensuse

I have tried the following:

Install with docker for leap 15.2
updated the pip  to version 20

used this for the install. pip install docker-compose

If I do this then the install occurs but does not ask for the wizard.  

it installs : iscard-entine, iscard-portal, isard-api, iscard=hypervisor, iscard-stacic, iscard-grafana, iscard-db, iscard-websockify, iscard-backend, iscard-webapp, iscard-redis, iscard-vpnn, iscard-squid.

it also never goes to the wizard

If I go with standard opensuse docker/compose, then I get the wisRd but it always fails to create the domain.

Any thoughts?

**Comment by transparent-DR** [comment]
I am now working through issues.

After I installed it, I have a hypervisor working.

The issue is that when I download domains, I get the following error.  

I would be thankful for any help on this matter

![image](https://user-images.githubusercontent.com/81203076/113085447-cecf6480-91ad-11eb-856d-aa07c583bdaf.png)

![image](https://user-images.githubusercontent.com/81203076/113085508-f3c3d780-91ad-11eb-9141-5c1628113bde.png)

![image](https://user-images.githubusercontent.com/81203076/113085534-02aa8a00-91ae-11eb-8c93-ea76e193df90.png)

**Comment by sim6** [comment]
Please,  due this is not about `docker-compose pull`, could you open a new issue and send the logs?

**Comment by sim6** [comment]
@transparent-DR thanks to open #391
