### ISSUE TITLE
Fail to login after update IsardVDI

### ISSUE THREAD

**Issue by fgonzalezmacias** [isard-vdi/isard#393]
Hello

I just to update my IsardVDI and now I can't to login:

![image](https://user-images.githubusercontent.com/72935746/114575849-e103d500-9c7a-11eb-9581-216fe76070b9.png)

And not as admin user

![image](https://user-images.githubusercontent.com/72935746/114576049-13153700-9c7b-11eb-963c-cdc79d54d6b4.png)

Thanks in advance

**Comment by sim6** [comment]
Please, colud you look at logs?

**Comment by sim6** [comment]
Maybe solved by https://gitlab.com/isard/isardvdi/-/merge_requests/158

**Comment by fgonzalezmacias** [comment]
Hello. Thanks for the update.

After update the system I can to login normal users, but the admin login, it's fail

![image](https://user-images.githubusercontent.com/72935746/115014263-645b3b80-9eb2-11eb-8d89-b350d938e4ed.png)

**Comment by sim6** [comment]
I guess this is due a missing database migration. Restart isard-engine to do it.
```
docker-compose restart isard-engine
```
But please, could you look at logs?

**Comment by fgonzalezmacias** [comment]
Hello.
I did docker-compose restart isard-endine unsuccessfully

I too reboot the server and the same problem

2021/04/20 08:13:17 360 - ERROR - try_isard-hypervisor: socket error, try if ssh is listen in hostname isard-hypervisor with ip address 172.19.0.13 and port 22
2021/04/20 08:13:17 375 - ERROR - try_isard-hypervisor: hypervisor isard-hypervisor failed when trying to connect
2021/04/20 08:13:17 375 - ERROR - try_isard-hypervisor: fail_connected_reason: socket error in ssh port, sshd disabled or firewall

This found in initdb.log

Maybe a firewall problem?

**Comment by fgonzalezmacias** [comment]
If it was a firewall problem, it would also affect the normal login, no?

I can login at http://miip/login with normal users

**Comment by sim6** [comment]
Since https://gitlab.com/isard/isardvdi/-/merge_requests/165 was merged, isard-engine doesn't write logs at `initdb.log` anymore. Please, could you look at `docker-compose logs`?

**Comment by fgonzalezmacias** [comment]
I just updated IsardVDI and apparently everything is ok.
My process is:

sudo wget https://isardvdi.com/docker-compose.yml

Download file docker-compose.yml.1

I remove the original docker-compose.yml and rename docker-compose.yml.1 to docker-compose.yml

docker-compose pull

I update and download all the images

docker-compose stop
docker-compose rm -f
docker-compose up -d

![image](https://user-images.githubusercontent.com/72935746/115528052-f5a32700-a291-11eb-8361-afb96d24cc05.png)

This is the content of opt/isard-local/logs/engine

The file initdb.log was update this morning. 

Are you commenting that this file should no longer be used by IsardVDI?

If this is so, is there something to be done by the user?

What is the location of the log files now?

Thanks

**Comment by fgonzalezmacias** [comment]
It was all a big mistake on my part, respecto to admin login

I was trying to enter to: https://my_isardvdi/login/isard-admin instead of https://my_isardvdi/isard-admin/login

![image](https://user-images.githubusercontent.com/72935746/115545822-8aaf1b80-a2a4-11eb-9919-2ac58114ce60.png)

I![image](https://user-images.githubusercontent.com/72935746/115546316-29d41300-a2a5-11eb-9505-a0f44ff9db37.png)

**Comment by fgonzalezmacias** [comment]
Is it normal not to be able to log into https: // my_isardvdi / login / isard-admin?

**Comment by sim6** [comment]
About logging:
We have logs in two locations. Most of them are at docker logs and some are at file logs in `/opt/isard-local/logs`.
Before https://gitlab.com/isard/isardvdi/-/merge_requests/165 engine logs are located at `/opt/isard-local/logs`.
When we will review and merge https://gitlab.com/isard/isardvdi/-/merge_requests/164 webapp logs will be written at docker logs also, so no more logs will be written in `/opt/isard-local/logs`.
You can read more information about docker logs at https://docs.docker.com/config/containers/logging/. If you would more support about logging, please, open a new issue. I prefer at https://gitlab.com/isard/isardvdi/-/issues. And you can use your favorite language. We understand Catalan, Spanish and English and maybe some others.

About login:
With URL `/login/isard-admin` you are login to `isard-admin` category, so you need to use users of `isard-admin` category if this category exists.

**Comment by fgonzalezmacias** [comment]
Ok, thanks.

The next issue will be open at gitlab.
