### ISSUE TITLE
Desktop Failed when applying QoS

### ISSUE THREAD

**Issue by juanfcomartin** [isard-vdi/isard#410]
Hi.
When I edit a desktop to set a network interface which has a QoS applied to it, its status changes to Failed, with the following status detailed info:

"Updating aborted, failed when updating xml from hardware dictionary"

I'm using the default Network QoS of "limit up and down to 1Mbps".

**Comment by sim6** [comment]
Thanks!
Duplidated of https://gitlab.com/isard/isardvdi/-/issues/260
