### ISSUE TITLE
Issues between creating a VM using an image and connecting to a VM created as a template

### ISSUE THREAD

**Issue by dndud2532** [isard-vdi/isard#426]
hello. I'm testing the IsardVDI environment.

I have below two problems between tests, can you help me?

#1. The following error occurs when connecting the VM created through the IsardVDI download service with the VNC viewer. can i know why?? (It doesn't seem to be a firewall issue as the same happens even if I access it directly from the server where IsardVDI is configured..)

### localhost connection deny error(ERR_CONNECTION_REFUSED) ###

#2. If you try to create a desktop using the ISO image after downloading the media, the following error occurs. How can I fix it?

![image](https://user-images.githubusercontent.com/12393391/184779428-33c84bdf-b37d-4540-9594-98d6ca6a2ee4.png)

P.S  
In addition, in the previous article, it seems that the guide document to configure Windows 10 has been provided by another issue, but the link to the file has expired and could not be checked. Can you provide a Win10 configuration guide?

Thank You.

**Comment by jvinolas** [comment]
> hello. I'm testing the IsardVDI environment.
> 
> I have below two problems between tests, can you help me?
> 
> #1. The following error occurs when connecting the VM created through the IsardVDI download service with the VNC viewer. can i know why?? (It doesn't seem to be a firewall issue as the same happens even if I access it directly from the server where IsardVDI is configured..)
> ### localhost connection deny error(ERR_CONNECTION_REFUSED)
If you start with the default isardvdi.cfg then the DOMAIN will be localhost and the viewers will only be reacheable from localhost. Change it to your IP/DNS and should be reacheable after build.sh and docker compose up -d again.
> 
> #2. If you try to create a desktop using the ISO image after downloading the media, the following error occurs. How can I fix it?
> 
> ![image](https://user-images.githubusercontent.com/12393391/184779428-33c84bdf-b37d-4540-9594-98d6ca6a2ee4.png)
> 
It seems you hitted this bug (https://gitlab.com/isard/isardvdi/-/merge_requests/1165). Do a docker compose pull and up again and see if the problem is solved.
> P.S In addition, in the previous article, it seems that the guide document to configure Windows 10 has been provided by another issue, but the link to the file has expired and could not be checked. Can you provide a Win10 configuration guide?
> 
> Thank You.

**Comment by dndud2532** [comment]
Thanks for your help.

With the method you provided, I was able to create a Win10 Desktop by accessing the Viewer and creating a Desktop through Media.

Afterwards, referring to the previous issue, I am creating a Win10 VM, but after Virtio is recognized, the boot disk is not recognized and cannot be created. Is there a guide to solve this part?

1. 
![image](https://user-images.githubusercontent.com/12393391/185042038-5119b3f3-d260-4b7d-851a-340753616bcc.png)

2.
![image](https://user-images.githubusercontent.com/12393391/185042099-54662728-a35a-4127-8797-b0de050a9b5c.png)

3.
![image](https://user-images.githubusercontent.com/12393391/185042167-e020a982-a872-4357-9af9-eb6ba91c0534.png)

4.
![image](https://user-images.githubusercontent.com/12393391/185042239-8e1e0a93-8199-4773-9ddb-b1f44339ae8c.png)

>> Windows cannot be installed on this disk. The hardware on this computer may not boot from this disk. Make sure you have enabled the disk's controller in your computer's BIOS menu.

referenced article

#181 
https://isard.gitlab.io/isardvdi-docs/install/first-steps/#win-guest




Thank you for your help as always.

**Comment by dndud2532** [comment]
Win10 configuration was carried out with the above contents. 

I will close the case Thank you.
