### ISSUE TITLE
 Inquiries about NVIDIA vGPU support

### ISSUE THREAD

**Issue by dndud2532** [isard-vdi/isard#427]
Hi, Thanks to your help, the test is going well.

If you have any questions, please contact us.

Currently, my server has NVIDIA A100 vGPU enabled, but within the IsardVDI portal, only A40 and P4 are checked in GPU Profile.

Is it possible to use other than the above two cards?

If it is available, how do I activate it?

![image](https://user-images.githubusercontent.com/12393391/187620706-e52d7978-113a-4a96-981b-aaeaf06e04e8.png)

![image](https://user-images.githubusercontent.com/12393391/187619974-e40a11ac-37d0-4165-90fb-0076762a2ad7.png)

#213

**Comment by alarraz** [comment]
Hi, 

can you copy/paste this script in your server and share the output?

https://gitlab.com/-/snippets/2400795


Alberto Larraz
IsardVDI

**Comment by dndud2532** [comment]
Hello, I wrote and executed the content of the script you sent me as follows.

![image](https://user-images.githubusercontent.com/12393391/188056253-ae7cafbb-24eb-45f2-a618-b6e9eca706f7.png)


I get the following output, is there anything else I need to check?

![image](https://user-images.githubusercontent.com/12393391/188056230-7441f9cc-9a4b-4cdc-a41c-c90ff29cc41b.png)

**Comment by alarraz** [comment]
Hello,

it seems that the script has not been executed. Have you executed previously in the hos this command?t

```
/usr/lib/nvidia/sriov-manage -e 00000000:c3:00.0
```

Then enter in the engine container and verify that script exists and execute inside:

```
docker exec -it isard-engine /bin/ash
```

inside the container:
```
/isard # ls -l info_nvidia.py
-rw-r--r--    1 root     root           192 Sep  1 16:11 info_nvidia.py

/isard # cat info_nvidia.py 
from engine.models.hyp import hyp
from pprint import pprint
h = self = hyp("isard-hypervisor",port=2022)
h.get_hyp_info(nvidia_enabled=True)
h.get_nvidia_capabilities()
pprint(h.info_nvidia)

/isard # python3 info_nvidia.py 
```
```

**Comment by dndud2532** [comment]
Hello, I ran the cmd you suggested as below, but the screen is the same as before. Am I missing something while running it?

![image](https://user-images.githubusercontent.com/12393391/188339695-a58a6b65-eddc-46ca-bbfe-4df11dde7c4d.png)
