### ISSUE TITLE
I can't change the IP of the Hypervisor

### ISSUE THREAD

**Issue by miguerus** [isard-vdi/isard#429]
Well, I solved the Hypervisor problem that restarted my entire installation.
The problem I have now is that I cannot connect to any viewer, since the Hypervisor appears to me as "localhost" and when I want to change the IP so that the viewers can find it, when I click ok and restart the isard-engine it returns to the value default.
I can't connect neither with Spice nor with RDP (they remain with the wheel turning), with nothing it connects.
Is there something I need to enable in order to make the change?

Thank you very much.

**Comment by jvinolas** [comment]
The viewers set automatically when hypervisor is autoregistering will be set to what it is set at https://gitlab.com/isard/isardvdi/-/blob/main/isardvdi.cfg.example#L40

By default it is `localhost`. You should set there your server IP or your DNS domain name reacheable from other hosts.

**Comment by miguerus** [comment]
I have tried to do that, but it doesn't work, the Hypervisor always returns to "localhost", if I do it from the web. And if I change the domain in isardvdi.cfg it also remains the same.

**Comment by jvinolas** [comment]
After making any change to your isardvdi.cfg (the copy of isardvdi.cfg.example) you have to:

1. ./build.sh (to recreate the docker-compose.yml based on those variables)
2. docker-compose up -d (to recreate containers which variables changed)

I've just updated this in [documentation](https://isard.gitlab.io/isardvdi-docs/install/configuration/)

**Comment by miguerus** [comment]
Thank you very much, it worked. But as it happens in this type of thing, when something is solved a new problem appears.
Every time I try to start an installation of a VM (whether on windows or linux, it's the same), when I open the viewer it starts consuming memory and restarts the entire operating system.
If I try to use Spice it does not enter the desktop and everything hangs, and if it is through the web browser, the same inconvenience.
I am using an Ubuntu Server 22.04 as host OS, 16GB Ram and 300GB HD, any suggestions? Thanks.

**Comment by jvinolas** [comment]
Well, with 16GB I don't know how many RAM are you assigning to your IsardVDI VM desktop, but allow for at least 2/3GB free, so set at much your VM to 13GB, but should be fine with 8GB usually if this computer is not consuming more ram with other processes.

It does not make sense that it hungs when opening the viewer. We are using thin clients like raspberrypi and start VMs of 4GB in our development laptop (8GB) without any problem.

**Comment by miguerus** [comment]
Ubuntu is a VM mounted on an XCP-NG server, and it has the specs I listed above.
The VM with Ubuntu is with active nested virtualization, so there should be no problem on that side.
The amount of memory allocated to the IsardVdi VM is 4GB and a disk is 80GB.
With all those specifications it generates that error.

**Comment by jvinolas** [comment]
Check dmesg and journalctl/syslog log messages when it crashes. There should be some kind of os/virtualization error.

**Comment by miguerus** [comment]
Well, I look at syslog with tail and this is what it shows when I run the VM on IsardVDI:

Sep  7 14:00:52 isardvdi kernel: [ 1185.071651] device vnet0 entered promiscuous mode
Sep  7 14:00:52 isardvdi kernel: [ 1185.071781] virbr0: port 1(vnet0) entered blocking state
Sep  7 14:00:52 isardvdi kernel: [ 1185.071782] virbr0: port 1(vnet0) entered listening state
Sep  7 14:00:52 isardvdi kernel: [ 1185.171167] device vnet1 entered promiscuous mode
Sep  7 14:00:54 isardvdi kernel: [ 1187.079659] virbr0: port 1(vnet0) entered learning state
Sep  7 14:00:56 isardvdi kernel: [ 1189.095587] virbr0: port 1(vnet0) entered forwarding state
Sep  7 14:00:56 isardvdi kernel: [ 1189.095590] virbr0: topology change detected, propagating
Sep  7 14:00:57 isardvdi systemd[1]: run-docker-runtime\x2drunc-moby-6df4e4008a8c4e62ed3f95cd4d48fdfb928646651eec535848dc6629ed4ae96e-runc.o6TMKQ.mount: Deactivated successfully.
Sep  7 14:00:57 isardvdi systemd[1]: run-docker-runtime\x2drunc-moby-0444b416325395b61f1ebfaaf016d83472282df04ad08d1def1238ccc6ed59bb-runc.cGuoTk.mount: Deactivated successfully.
Sep  7 14:01:01 isardvdi systemd[1]: run-docker-runtime\x2drunc-moby-7f45df429db6009a65909d5daac45131cd84cef1d5d14a9b2337092014e07410-runc.XDAlYB.mount: Deactivated successfully.

**Comment by miguerus** [comment]
I discover what was the problem.
On one VM on IsardVdi had selected 2 networks at the same time.
That cause the problem to reboot the Ubuntu host. Now I`ll try to solve the problem of the booting device, cus I select the ISO of the OS and the ISO of the drivers (virtio ISO drivers) but when the VM boots, only appear "not bootable device".

**Comment by jvinolas** [comment]
Have you set boot to 'cd/dvd' instead of 'hard disk' when editing the new desktop?

Also check that the first iso set is the one with the OS.

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
