### ISSUE TITLE
Docker network change and AD LDAP authentication method

### ISSUE THREAD

**Issue by dndud2532** [isard-vdi/isard#430]
Hi team,

I have the following issues between the environment configurations: Can I apply? 

#1. 
The VM test for the existing default network was completed normally, but if the isardvdi.cfg file is changed to the internal test band, there is a problem that isard-api becomes abnormal between docker-compose up.

![image](https://user-images.githubusercontent.com/12393391/192667932-ebb23fb4-930e-4052-8d10-7e8372eba35a.png)

Is there any workaround for the above problem?

#2.
I am trying to configure LDAP authentication through an internally configured AD server. It seems to be activated through the isardvdi.cfg file. Is there a detailed guide?

If yes, please let me know in the comments.

Thank you.

**Comment by jvinolas** [comment]
Sorry, we are mostly reviewing issues at gitlab.com/isard/isardvdi

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
