### ISSUE TITLE
Using Isardvdi in different port (No port linking in RDP Viewer Page)

### ISSUE THREAD

**Issue by felixcharles** [isard-vdi/isard#431]
`# ------ Video external NAT ports --------------------------------------------
## their guests started in this hypervisor? (outside NAT ports)
VIEWER_SPICE=82
VIEWER_BROWSER=8082
VIEWER_RDPGW=9999
`
I am using a different port in isardvdi.cfg and after generating the docker-comsose.yml. I also change the published ports of isard network to 82 and 443.

The ISARD-PORTAL opens up and works perfectly fine with port # 8082 and even my certificate works.
But when I click on the "RDP Browser Viewer" Button to login into the VM. The new page opens without the port # 8082.
Please tell me how can , I change the port as my host is using port # 80&443 for apache. Therefore, I want to use port 82 and 8082 (https)

Please check the attached screenshots, every-time I have to put 8082 in port when redirected by "RDP Browser Viewer" Button.

![Image1](https://i.ibb.co/5TvW3kw/1.jpg)
![Image2](https://i.ibb.co/QMsnHn5/2.jpg)
![Image3](https://i.ibb.co/VS3Kg5q/3.jpg)

**Comment by jvinolas** [comment]
https://gitlab.com/isard/isardvdi/-/issues/599
