### ISSUE TITLE
Put an eye on password field to be able to see it

### ISSUE THREAD

**Issue by pabloruizsoria** [isard-vdi/isard#441]

**Comment by jvinolas** [comment]
Yes, will be helpful. We added in our ticketing system.

Sorry for late delay, we mostly review issues at gitlab.com/isard/isardvdi

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
