### ISSUE TITLE
Ajax Error

### ISSUE THREAD

**Issue by Youngseo-Jeon0313** [isard-vdi/isard#447]
I want to go into Administrator and get Downloads. But the infinite loading is happening. I looked at the developer tool and found the following error.

"Failed to load resource: The Server Responded with a Status of 500 (). EASE See http://datatables.net/tn/7 "

Then I went to https: // {My IP}: 8890/api/v3/admin/downloads. I don't know what this is.

`
{"data":"","debug":"","description":"Authorization header is expected","description_code":"unauthorized","error":"unauthorized","function":"tokens.py:51:get_token_header","function_call":"tokens.py:74:get_token_auth_header","msg":"Unauthorized","params":null,"request":"----------- REQUEST START -----------\nGET http://172.28.4.244:8890/api/v3/admin/downloads\r\nHost: 172.28.4.244:8890\r\nSec-Ch-Ua: \"Google Chrome\";v=\"119\", \"Chromium\";v=\"119\", \"Not?A_Brand\";v=\"24\"\r\nSec-Ch-Ua-Mobile: ?0\r\nSec-Ch-Ua-Platform: \"Windows\"\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.6045.159 Safari/537.36 NetHelper70\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7\r\nSec-Fetch-Site: none\r\nSec-Fetch-Mode: navigate\r\nSec-Fetch-User: ?1\r\nSec-Fetch-Dest: document\r\nAccept-Encoding: gzip, deflate, br\r\nAccept-Language: ko,en-US;q=0.9,en;q=0.8\r\nCookie: username-172-28-4-244-30002=\"2|1:0|10:1698811499|27:username-172-28-4-244-30002|44:YmY2OTQ1YzBhYzNiNGJmYjg5ZmQzMDJkNmVhN2IxMjY=|eb7cdcee1773eec151680e6f1d0c943d8ff83864a74ef0bdd17bcfef26e7833c\"; session=.eJwljrsKwzAMAP_FcwOSI8t2fiZItkQDaQt5TKX_3kCWG2447htm32x_hunYTnuEeelhCgQaQRroWIwZpQhxQadRqCVMgJyxJ0lmRgqsZrk71Oija6pEWCtalVZyBfbLMXGO3ChxjIrgwhIBY-Heya4sqlQwyRoRbIRwjZy7bffN-mmyDt1czvUYpL-W983w-wNaNjfZ.ZVr67w.IoeEai3MY1_XMbQwOVQ-_OnDf80\r\nX-Forwarded-For: 172.28.4.105\r\nConnection: close\r\n\r\n----------- REQUEST STOP  -----------"}`

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
