### ISSUE TITLE
Problema con hypervisor

### ISSUE THREAD

**Issue by dfcaicedo** [isard-vdi/isard#450]
Me encuentro probando, y realicé una instalación minima de ubuntu server 22.04 lts, ejecuto los pasos por defecto, usando los mismos datos del archivo cfg de ejemplo, y me aparece en la lista de hypervisores "System Error: No hypervisor available." adicional que no me deja realizar más operaciones, el equipo antes corría un proxmox con varias maquinas virtuales y si está con el soporte para maquinas virtuales desde la bios, agradezco la colaboración

**Comment by sim6** [comment]
Please could you inspect `docker-compose logs isard-hypervisor isard-api`.

**Comment by dfcaicedo** [comment]
Me genera estos datos
[logs.txt](https://github.com/isard-vdi/isard/files/14728245/logs.txt)

**Comment by jvinolas** [comment]
Sorry, but could you try with a more recent version?

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
