### ISSUE TITLE
Media - Upload from URL only HTTPS allowed ?

### ISSUE THREAD

**Issue by markomdinic** [isard-vdi/isard#451]
Why on earth would you hardcode https enforcement for media upload URLs, especially when that https also requires a valid cert ? I don't know it that has always been the case, but now definitely is. If one wants to upload an ISO or a virtual disk image from a home machine, they need to have a web server fully set up for https, along with a valid certificate, which also implies a valid domain. Not every enthusiast out there is able or willing to go to such lenghts just to check out the project.

Shouldn't enforcement of such limiting factor be left for administrators to decide ?

**Comment by sim6** [comment]
This policy was introduced in [v11.29.22](https://gitlab.com/isard/isardvdi/-/releases/v11.29.22). In a future we will replace this feature to download an ISO to one that allow upload an ISO via the web browser. But if you want a configuration option to bypass this policy please request it via https://gitlab.com/isard/isardvdi/-/issues/new.

**Comment by sim6** [comment]
@markomdinic can we close this issue?

**Comment by acarfer940** [comment]
> @markomdinic can we close this issue?

FYI: I've created an specific feature to allow HTTP connections in the media import form. 

https://gitlab.com/isard/isardvdi/-/issues/675

I'm not an expert in IsardVDI because I've started to use it few months ago, but if it's useful, maybe I can take care of this and make a first PR to check by the main developers of the solution.

**Comment by markomdinic** [comment]
> @markomdinic can we close this issue?

Sorry for late reply ... I really have to reduce the number of email accounts i need to shuffle ....  

Anyway, yes, thank you, you can close it.
