### ISSUE TITLE
Create new media- the format of the given URL is not valid.

### ISSUE THREAD

**Issue by mcmib** [isard-vdi/isard#452]
Hello Bro,

We used FreeNAS as our external storage server.
A self-signed certificate is imported to the FreeNAS server, and browsers can visit through it via WebDAV protocol.
The extra_hosts part of the file docker-compose.yml has been updated. 
However, IasrdDVI prompts an error message when I create a new media, saying the format of the given URL is not valid, as shown in the attached file.

I could not find solutions in the official documentation.

I would appreciate it if anyone could provide a solution. 

Best,

Peter
![Snipaste_2024-04-24_09-46-36](https://github.com/isard-vdi/isard/assets/33493053/93767c6a-ab7e-47bb-b691-d2968abf38e0)

**Comment by sim6** [comment]
Please see https://github.com/isard-vdi/isard/issues/451#issuecomment-2035582179
