### ISSUE TITLE
How to build an Old Version like v8 in Ubuntu 22

### ISSUE THREAD

**Issue by e-munivel** [isard-vdi/isard#453]
Hi, How to build an old version/tag like v8  or v9 in Ubuntu 22

**Comment by sim6** [comment]
You can build it via the following commands:
```
git clone https://gitlab.com/isard/isardvdi.git -b v8.0.0
cd isardvdi
cp isardvdi.cfg.example isardvdi.cfg
echo "USAGE=build" >> isardvdi.cfg
./build.sh
docker-compose build
```
Alternatively you can download docker images, instead of build it, by configuring `DOCKER_IMAGE_TAG=v8-0-0` in `isardvdi.cfg` and running `./build.sh && docker-compose pull`.

Please could you explain why you are not using the last version?

**Comment by e-munivel** [comment]
Thank you, but DB is not getting up and getting the following error... (but healthcheck is there in Dockerfile)

_"dependency failed to start: container isard-db has no healthcheck configured"_

**Comment by e-munivel** [comment]
isard-portal also getting down, and log is as follows,

_<string>:1: DeprecationWarning: 'crypt' is deprecated and slated for removal in Python 3.13
[NOTICE]   (1) : haproxy version is 2.8.9-1842fd0
[ALERT]    (1) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:114] : error detected in frontend 'fe_secured' while parsing 'http-response add-header' rule : expects exactly 2 arguments.
[ALERT]    (1) : config : Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg_

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
