### ISSUE TITLE
I can´t download

### ISSUE THREAD

**Issue by Minibomba2** [isard-vdi/isard#454]
Hello, I've been trying to download a couple of ISO images for a few days and the process keeps starting. I also can't delete and try again since it is detected that they are downloading. I have tried to solve it with a post that says to stop and delete the libvirtd service but this service is not found on my system. Any way to solve it?

![image](https://github.com/isard-vdi/isard/assets/63346689/9278b046-5aa2-4b81-9f9f-b3e7d53c6d40)

**Comment by sim6** [comment]
Do you have any hypervisor registered in the system (Administration/Infrastructure/Hypervisors)?

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
