### ISSUE TITLE
Creating a Desktop without Template

### ISSUE THREAD

**Issue by gloatoriginal** [isard-vdi/isard#455]
I'm confused on how to initially start. It almost seems like I need to download templates to than create a desktop from the template, to than flip around and create a template from that desktop?

Is there a way to create a desktop and I walk through installing the OS, than I create a template after? this seems very confusing from a virtualization administration standpoint because I"m caught in a chicken and the egg situation ie. I need a desktop to create a template, but in order to create a desktop I need a template..

**Comment by sim6** [comment]
Currently a template only can be created from a desktop. A desktop can be created form a template but also from a media. The media can be downloaded from an external website. Also, media and desktops can be downloaded from Administration/Downloads section.

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
