### ISSUE TITLE
unable to add an external hypervisor 

### ISSUE THREAD

**Issue by mcmib** [isard-vdi/isard#456]
Hello all,
I am reaching out for assistance with my IsardVDI setup. I have successfully installed IsardVDI on one server (SRV01) and am currently attempting to configure a hypervisor on a second Ubuntu server (SRV02) by following the document:
https://isard.gitlab.io/isardvdi-docs/admin/hypervisors/#manual-install

After execution of the following command on the SRV01, 
docker exec -e HYPERVISOR=<IP|DNS> -e PASSWORD=<YOUR_ROOT_PASSWD> isard-engine bash -c '/add-hypervisor.sh'

I got a message saying that Hypervisor ssh access was granted.

Trying to ssh into 192.168.3.136...
# 192.168.3.136:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.10
# 192.168.3.136:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.10
# 192.168.3.136:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.10
# 192.168.3.136:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.10
# 192.168.3.136:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.10
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/root/.ssh/id_ed25519.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
expr: warning: '^ERROR: ': using '^' as the first character
of a basic regular expression is not portable; it is ignored
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys

Number of key(s) added: 1

Now try logging into the machine, with:   "ssh -p 22 'administrator@192.168.3.136'"
and check to make sure that only the key(s) you wanted were added.

Hypervisor ssh access granted.

However,  it seems that it stuck without any error messages after adding SRV01 on the UI webpage.
![Snipaste_2024-07-10_15-30-23](https://github.com/isard-vdi/isard/assets/33493053/ca6ac2a0-2f37-4bb0-9501-b4953c7925b6)

Any guidance or instructions to resolve these problems would be greatly appreciated.

**Comment by jvinolas** [comment]
I've just added an [infrastructure guide](https://isard.gitlab.io/isardvdi-docs/install/infrastructure/)

Hope it helps!

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
