### ISSUE TITLE
Cannot create multi-server setup

### ISSUE THREAD

**Issue by Zopazz** [isard-vdi/isard#457]
Hi.

I am currently completely unable to create a multi server setup.

I have 2 hosts:

IVDI-MANAGER-01 -\> Web server, which is created with the web flavour
IVDI-HYPERVISOR-01 -\> Hypervisor, which is created with the hypervisor flavour

Currently for testing purposes both of them are exposed completely to the internet, to avoid issues.

I have also forwarded port 2022 on the hypervisor, so the web server can connect and port 6379 on the web server, so the hypervisor can connect back to it, for storage purposes.

I can create the hypervisor and register it correctly with the manager. I can install media and create a desktop. But when I spawn the desktop with novnc I just get a blank screen saying the connection is closed.

I can see it tries to connect to the a path like the following, but receives a 503 error in return: 
wss://\<my webserver IP\>/isard-hypervisor/5902/\<token\>

The changes on my web server to the config currently is:
FLAVOUR=web
DOMAIN=\<web server IP\>
WEB_APP_ADMIN_PW=\<my PW\>
WEB_APP_SESSION_SECRET=\<my secret\>
API_ISARDVDI_SECRET=\<my secret\>
API_HYPERVISORS_SECRET=\<my secret\>
API_DOMAIN=\<web server IP\>
VPN_DOMAIN=\<web server IP\>

My changes to the hypervisor configuration is the following:
FLAVOUR=hypervisor
DOMAIN=\<hypervisor ip\>
WEB_APP_ADMIN_PWD=\<same as web server's\>
API_ISARDVDI_SECRET=\<same as web server's\>
API_HYPERVISORS_SECRET=\<same as web server's\>
API_DOMAIN=\<web server IP\>
VPN_DOMAIN=\<web server IP\>
VIDEO_DOMAIN=\<web server IP\>
STORAGE_DOMAIN=\<hypervisor IP\>
REDIS_HOST=\<web server IP\>
HYPER_ID=\<randomly generated name prefixed with IVDI-AGENT- and uuidgen\>

I can not see what I'm doing wrong or what I'm missing to make these connect together so I can get video

The issue persists whether the VIDEO_DOMAIN variable is set to the web server, the hypervisor or nothing.

What am I missing?

PS. If you can help me make this work, I'll gladly create a short guide for the documentation for creating multi-server installations, as far as I can see none exists :)

Thank you in advance.

**Comment by jvinolas** [comment]
I've just added an [infrastructure guide](https://isard.gitlab.io/isardvdi-docs/install/infrastructure/)

Hope it helps!

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
