### ISSUE TITLE
Maybe documentation lacks some kind of "how to configure a 'recommended' hardware/software infrastructure" to run Isard on it, then

### ISSUE THREAD

**Issue by q2dg** [isard-vdi/isard#5]
I mean, from your presentation in RedIRIS: 

*How to get to use 46 cpus / 98 threads?"
*How to get to use the 576GB of RAM?"
*How to get to use 16TB on 2 NAS cluster?"

Specifically, I'm really puzzled about how to achieve these incredible numbers (46 cpus, 576GB of RAM, uau!!) with "standard" PCs. 

What kind of hardware server pool do you recommend and whick kind of cluster software must be running on it (DRBD+Pacemaker I've seen, I think...)...?

Thanks!

**Comment by NefixEstrada** [comment]
Hey there!

First of all sorry for being **this** late. I'm not sure if you are still interested in the question, but I'm going to answer it anyway. IsardVDI uses a pool of Hypervisors. Before each desktop starts, IsardVDI checks for the best hypervisor candidate (the one that has less load, normally) and starts the desktop there. You can setup as many hypervisors as you need and scale that way. We currently have 6 hypervisors but maybe that's too overkill for your needs.

For the storage part, you need to have the same storage pool shared in all the hypervisors. We have a cluster with DRBD9 + Pacemaker all connected with 10 Gbit networking but, depending on your needs, you might not need that.

Also, we encourage you to check out our last release, IsardVDI 1.0.0!! It has a huge amount of new features and bug fixes!!

Happy new year!
