### ISSUE TITLE
Download a update if a previous download action failed

### ISSUE THREAD

**Issue by alarraz** [isard-vdi/isard#66]
When a download has failed, the state of the domain or resource change to DownloadFailed, after that the web don't let download again @jvinolas

**Comment by jvinolas** [comment]
The thing to discuss here is: why the donwload failed? I assume there may be many situations where a download may fail. Do we have to threaten all them identically?

One option is to let the user start download again and also delete it. If we set the status to Deleting from DownloadFailed, it will work at engine level?

**Comment by jvinolas** [comment]
I've checked and we have a mismatch in this state definition as I found it as FailedDownload to be correctly controlled by UI but a mix of FailedDownload and DownloadFailed within engine.

We should continue using FailedDownload
