### ISSUE TITLE
Last access time in the profile page is in an incorrect format

### ISSUE THREAD

**Issue by NefixEstrada** [isard-vdi/isard#67]
It's in a timestamp format, not in a human readable format
![screenshot_2019-01-24 isard vdi](https://user-images.githubusercontent.com/22214853/51680470-28421480-1fe2-11e9-8c2e-446c342f4aa7.png)

**Comment by jvinolas** [comment]
I'm not sure about continue using moment.js. We must evaluate again: https://github.com/you-dont-need/You-Dont-Need-Momentjs

**Comment by NefixEstrada** [comment]
Yeah, `moment.js` might be too overkill for our needs

**Comment by b-barry** [comment]
``date-fns`` is a good alternative to moment.js and easier to manage

**Comment by NefixEstrada** [comment]
Seems promising! We'll check it out again when we rebuild the profile page with Vue

**Comment by sim6** [comment]
Is it really useful to have on your profile page the time when you logged in? Maybe we can remove this information from your profile page.

**Comment by NefixEstrada** [comment]
Yes, I also think that this feature isn't needed at all, and if we could avoid adding a dependency would be great.

Basically, the profile page is only for viewing your groups, roles, categories... and for changing the password. It could be redesigned from scratch to enhance this and avoid having that much of space without using it.

**Comment by NefixEstrada** [comment]
#176 has been merged, this issue can be closed now
