### ISSUE TITLE
Change from Dowloaded to Deleting in media list

### ISSUE THREAD

**Issue by alarraz** [isard-vdi/isard#71]
In media files list (3rd element in main menu, not in Updates) don't change from Downloaded to Deleting when x icon is pressed

**Comment by jvinolas** [comment]
You mean that the delete icon should be disabled while not in Stopped state?

**Comment by jvinolas** [comment]
I see now that we don't let removing those isos as there is no procedure to remove it from all the domains. I'll try to fix that by 1.1.0

**Comment by jvinolas** [comment]
This is fixed in #118
