### ISSUE TITLE
please help me FailedCreatingDomain?	

### ISSUE THREAD

**Issue by gypsy147** [isard-vdi/isard#95]
Hi im got status FailedCreatingDomain and i dont know how to config??

**Comment by jvinolas** [comment]
You may check:
1. Active virtualization. Check if your host hardware is able to virtualize and it is also activated in BIOS. [requirements](https://isardvdi.readthedocs.io/en/latest/install/install/#requirements)
2. Hypervisor up and running in hypervisor menu.
3. Check desktop details (open details desktop clicking in it's + left sign) and check it's detail status. You may find there that your hardware does not support vmx/svm virtualization or other failed status.

If everything else is correct (you have virtualization activated), you may update to latest version:

> docker-compose down
> git pull
> docker-compose pull
> docker-compose up -d

 and check again.

**Comment by gypsy147** [comment]
Thank you now i change server cloud for test
